### ISSUE TITLE
Using <StrictMode /> causes error in console: `Warning: Unsafe lifecycle methods were found within a strict-mode tree`

### ISSUE THREAD

**Issue by JustFly1984** [gatsbyjs/gatsby#10179]
I'm using gatsby as example environment for new google maps api, and I need to test it with SSR, but at the same time I need to test it in strict mode, but instead of showing me errors in my own code, it errors out on `gatsby's` code.

```
Warning: Unsafe lifecycle methods were found within a strict-mode tree:
    in StrictMode (at pages/index.js:66)
    in IndexPage (created by PageRenderer)
    in PageRenderer (created by JSONStore)
    in JSONStore (created by EnsureResources)
    in ScrollContext (created by EnsureResources)
    in RouteUpdates (created by EnsureResources)
    in EnsureResources (created by RouteHandler)
    in RouteHandler (created by Root)
    in div (created by FocusHandlerImpl)
    in FocusHandlerImpl (created by Context.Consumer)
    in FocusHandler (created by RouterImpl)
    in RouterImpl (created by LocationProvider)
    in LocationProvider (created by Context.Consumer)
    in Location (created by Context.Consumer)
    in Router (created by Root)
    in Root
    in _default (created by HotExported_default)
    in AppContainer (created by HotExported_default)
    in HotExported_default

componentWillMount: Please update the following components to use componentDidMount instead: SideEffect(NullComponent)

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
```

**Comment by jonniebigodes** [comment]
That's because and i'm just guessing, as i'm not knowledgeable of all the gatsby code, but deep down somewhere in some components used in gatsby, or one of the libraries you're using, there might be some now deprecated methods being used. And correcting that might take some time as the React ecosystem is constantly evolving and not only gatsby, but other libraries also, will take some time to adjust to this constant evolution.
But does the build break, or does it succeed but with the warnings?

**Comment by JustFly1984** [comment]
I hadn't tried to build for prod with <StrictMode /> yet, it warns in develop only.

**Comment by jonniebigodes** [comment]
I'm inclined to say that this will happen in production mode as well.
You're probably going to get the same warnings.
But it's currently working, even with the warning? That's what i wanted to ask aswell

**Comment by JustFly1984** [comment]
It is warning, not an error, so yes it does not crush an app by itself, but if you have scripts, which tracking errors, it spams a system with false negatives, and google lighthouse audit tool lowers your performance grade. Console.log is not cheap IO operation, especially with warnings.

**Comment by pieh** [comment]
> but instead of showing me errors in my own code, it errors out on gatsby's code.

Actually that's not entirely true - it shows "stack trace" which originates from gatsby runtime, but actually end up in your code:

```
Warning: Unsafe lifecycle methods were found within a strict-mode tree:
    in StrictMode (at pages/index.js:66) // this points to your code
    in IndexPage (created by PageRenderer) // IndexPage is your component
    in PageRenderer (created by JSONStore)
```

```
componentWillMount: Please update the following components to use componentDidMount instead: SideEffect(NullComponent)
```

Do You perhaps use https://github.com/gaearon/react-side-effect ? (or maybe some of your dependencies use it)

**Comment by JustFly1984** [comment]
not stale

**Comment by JustFly1984** [comment]
Please reopen

**Comment by diegohaz** [comment]
I'm getting the following error with `StrictMode`:
![image](https://user-images.githubusercontent.com/3068563/53034045-32282d80-3451-11e9-858f-1d30cde20134.png)

**Comment by JustFly1984** [comment]
not stale

**Comment by PutziSan** [comment]
One option would be to use [react-helmet-async](https://github.com/staylor/react-helmet-async) as an alternative to react-helmet.

**Comment by JustFly1984** [comment]
How to deprecate `react-helmet` for gatsby projects, if for example somebody imports helmet from sub-dependencies gatsby, it could break the build. This looks like breaking change issue.

**Comment by selbekk** [comment]
This issue will now hit a lot more consumers, due to React 16.9.

**Comment by JustFly1984** [comment]
Yes, this bummers me to update react in my gatsby project

**Comment by JustFly1984** [comment]
https://github.com/nfl/react-helmet/issues/426

**Comment by sever1an** [comment]
Has anybody looked into using react-helmet-async as a replacement? This article by the creator cites the lack of activity at react-helmet as a major motivation for a fork:

https://open.nytimes.com/the-future-of-meta-tag-management-for-modern-react-development-ec26a7dc9183

At this point react-helmet-async has as many weekly downloads as react-helmet.

https://www.npmjs.com/package/react-helmet-async

**Comment by sever1an** [comment]
I have run a brief experiment into using react-helmet-async with Gatsby and find that it is rather easy to use. It basically just needs a context, which can be added in gatsby-browser.js:

```
// gatsby-browser.js
import React from 'react';
import { HelmetProvider } from 'react-helmet-async';

let helmetContext = {};
export const wrapRootElement = ({ element }) => {
  return <HelmetProvider context={helmetContext}>{element}</HelmetProvider>;
};
```

To use <Helmet> in components the import simply needs to be changed to use react-helmet-async
```
import { Helmet } from 'react-helmet-async';
```

I am not sure this would not be a breaking change for some gatsby-plugin-react-helmet users. At the very minimum `Helmet.renderStatic()` would not exist any longer.

**Comment by sever1an** [comment]
I have briefly experimented with what a plugin supporting helmet-async might look like, and it seems quite simple. This hypothetical plugin would basically emulate the redux plugin, because the only real difficulty is wrapping the root element in a helmet context.

**wrap-with-helmet-provider.js**
```
import React from 'react';
import { HelmetProvider } from 'react-helmet-async';

let helmetContext = {};
export default ({ element }) => {
  return <HelmetProvider context={helmetContext}>{element}</HelmetProvider>;
};
```

**gatsby-ssr.js and gatsby-browser.js**
These use the similar-and-complementary APIs for wrapRootElement, so would be identical. 
```
import wrapWithHelmetProvider from './wrap-with-helmet-provider';
export const wrapRootElement = wrapWithHelmetProvider; 
```

**package.json**
This would contain the minimum boilerplate and peerDependencies for react-helmet-async and gatsby.

**README.md**
The only difference using this plugin vs gatsby-plugin-react-helmet is that the async package would need to be imported to use `<Helmet>`

`import { Helmet } from 'react-helmet-async';`

**Comment by wardpeet** [comment]
@sever1an thank you for taking the time to write such a comprehensive post. Sadly we're not able to move away from react-helmet in v2 as it would be a breaking change with gatsby-plugin-react-helmet.

What's the reason to use StrictMode?

**Comment by narration-sd** [comment]
_underline_ this, no??
> It would be nice if react-helmet updated its dependencies such that they all used the new name UNSAFE_componentWillMount(). This would eliminate the warnings for now, and generally push the day when a react update breaks gatsby builds into the future.

Hope you can do this now - just think of all the time we spend tracking this down...and the support load for other systems or benefitting by upgrading Gatsby - thanks

**Comment by josephrexme** [comment]
It's hard to tell what the rationale is from this thread. I tried using `react-helmet-async` and it seemed to have been just fine without errors. The probably then became that `gatsby-plugin-react-helmet` still relies on `react-helmet` and would lead to stale page titles. I had to go back to `react-helmet` since it still behaves as expected except I would like to get rid of the console warning.

**Comment by aoberoi** [comment]
> @sever1an thank you for taking the time to write such a comprehensive post. Sadly we're not able to move away from react-helmet in v2 as it would be a breaking change with gatsby-plugin-react-helmet.

@sever1an out of curiosity, why are we not open to a breaking change to fix this issue? i took a look at several other plugins in the repo, and as of now they are not all synchronized on major versions, so that reason seems unlikely.

**Comment by nikoladev** [comment]
> @sever1an thank you for taking the time to write such a comprehensive post. Sadly we're not able to move away from react-helmet in v2 as it would be a breaking change with gatsby-plugin-react-helmet.
> 
> What's the reason to use StrictMode?

@wardpeet Would it be possible to add this to [the milestone for the next major version](https://github.com/gatsbyjs/gatsby/milestone/5)?

**Comment by robinmetral** [comment]
Seems like parts of the community is already opting for [gatsby-plugin-react-helmet-async](https://www.gatsbyjs.org/packages/gatsby-plugin-react-helmet-async/).

To move forward with this issue, maybe we could update the docs, switch the default meta tag manager in the official Gatsby starters... and eventually deprecate `gatsby-plugin-react-helmet` in favor of `gatsby-plugin-react-helmet-async`? What do you think?

**Comment by sever1an** [comment]
The async helmet plugin should be official, not community contributed. react-helmet is vaporware

**Comment by m-allanson** [comment]
This problem has been fixed by the release of React Helmet v6. `gatsby-plugin-react-helmet` has already [been updated to support the new version](https://github.com/gatsbyjs/gatsby/pull/22993) (thanks to @stevenocchipinti 🎉). 

To update your site:

- install `gatsby-plugin-react-helmet@3.2.2` or later
- install `react-helmet@6.0.0` or later
- ensure you're using a named import when you import the Helmet component `import { Helmet } from "react-helmet"`

**Comment by simnalamburt** [comment]
@diegohaz FYI, discussion of gatsby-react-router-scroll is being continued at https://github.com/gatsbyjs/gatsby/issues/21231, and a PR regarding this issue has been opened! https://github.com/gatsbyjs/gatsby/pull/21626

**Comment by simnalamburt** [comment]
As @m-allanson pointed out, react-helmet has released a new release fixing this issue. I think this issue is now OK to be closed

**Comment by JustFly1984** [comment]
@simnalamburt closing

**Comment by cutiful** [comment]
@m-allanson but it wasn't fixed? Getting
```
Warning: Using UNSAFE_componentWillMount in strict mode is not recommended and may indicate bugs in your code. See https://reactjs.org/link/unsafe-component-lifecycles for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.

Please update the following components: SideEffect(NullComponent)
```

with react-helmet 6.1.0 and gatsby-plugin-react-helmet 4.14.0.

See https://github.com/nfl/react-helmet/issues/548 and the comments on https://github.com/nfl/react-helmet/issues/426 (after it was closed). Helmet still depends on react-side-effect, which still uses `UNSAFE_componentWillMount`: https://github.com/gaearon/react-side-effect/issues/54.
