### ISSUE TITLE
Decorators causes Gatsby to crash

### ISSUE THREAD

**Issue by rossPatton** [gatsbyjs/gatsby#129]
Was hoping to use https://github.com/FormidableLabs/radium with gatsby to make hover states and media queries much easier, but attempting to use the @Radium decorator causes gatsby to choke.

when I remove the decorator gatsby works

edit: posted the wrong err

```
Debug: internal, implementation, error
    Error: Uncaught error
  at Object.exports.create (/Users/rosspatton/.nvm/versions/node/v4.1.0/lib/node_modules/gatsby/node_modules/hapi/node_modules/boom/lib/index.js:21:17)
  at Object.exports.internal (/Users/rosspatton/.nvm/versions/node/v4.1.0/lib/node_modules/gatsby/node_modules/hapi/node_modules/boom/lib/index.js:254:92)
  at Object.exports.badImplementation (/Users/rosspatton/.nvm/versions/node/v4.1.0/lib/node_modules/gatsby/node_modules/hapi/node_modules/boom/lib/index.js:290:23)
  at _error (/Users/rosspatton/.nvm/versions/node/v4.1.0/lib/node_modules/gatsby/node_modules/hapi/lib/protect.js:53:28)
  at Domain.<anonymous> (/Users/rosspatton/.nvm/versions/node/v4.1.0/lib/node_modules/gatsby/node_modules/hapi/lib/protect.js:27:20)
  at emitOne (events.js:77:13)
  at Domain.emit (events.js:169:7)
  at Domain.errorHandler [as _errorHandler] (domain.js:84:19)
  at process._fatalException (node.js:208:33)
```

**Comment by rossPatton** [comment]
actually it appears to be a little more interesting than just the decorator

the decorator by itself doesn't cause problems, it's when I try to use radium specific styles like ':hover', etc.

**Comment by KyleAMathews** [comment]
Hey @rossPatton I just pushed a new release with a bunch of upgrades. Could you try upgrading and see how things are working now?

**Comment by rossPatton** [comment]
I've updated to `0.8.4` and now I'm getting a different error :(

```
ERROR in ./~/gatsby/dist/utils/web-entry.js
Module build failed: ReferenceError: Unknown plugin "react-transform"
  at PluginManager.subnormaliseString (/Users/ross/Developer/workspace/test-gatsby/node_modules/gatsby/node_modules/babel-core/lib/transformation/file/plugin-manager.js:147:13)
  at PluginManager.add (/Users/ross/Developer/workspace/test-gatsby/node_modules/gatsby/node_modules/babel-core/lib/transformation/file/plugin-manager.js:190:40)
  at File.buildTransformers (/Users/ross/Developer/workspace/test-gatsby/node_modules/gatsby/node_modules/babel-core/lib/transformation/file/index.js:237:21)
  at new File (/Users/ross/Developer/workspace/test-gatsby/node_modules/gatsby/node_modules/babel-core/lib/transformation/file/index.js:139:10)
  at Pipeline.transform (/Users/ross/Developer/workspace/test-gatsby/node_modules/gatsby/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
  at transpile (/Users/ross/Developer/workspace/test-gatsby/node_modules/gatsby/node_modules/babel-loader/index.js:12:22)
  at Object.module.exports (/Users/ross/Developer/workspace/test-gatsby/node_modules/gatsby/node_modules/babel-loader/index.js:71:12)
```

**Comment by KyleAMathews** [comment]
Check out the upgrade guide, there's some new packages you need to install https://github.com/gatsbyjs/gatsby/releases/tag/v0.8.3

**Comment by rossPatton** [comment]
Cool, so I followed that and the error is gone now. Unfortunately the issue with Radium still exists

**Comment by KyleAMathews** [comment]
@rossPatton could you push to Github your setup w/ radium where there's a crash so I could take a look at it?

**Comment by KyleAMathews** [comment]
@rossPatton if this is still a problem, feel free to reopen!

**Comment by KyleAMathews** [comment]
Fixed in https://github.com/gatsbyjs/gatsby/pull/279 and released in 0.11
