### ISSUE TITLE
ValidationError "siteMetadata" is not allowed

### ISSUE THREAD

**Issue by TuBl** [gatsbyjs/gatsby#14580]
![a](https://user-images.githubusercontent.com/50697784/59020441-01111480-8818-11e9-80f4-42573b902411.PNG)
![b](https://user-images.githubusercontent.com/50697784/59020450-053d3200-8818-11e9-8eda-78275ac0de33.PNG)

as shown in the pictures, i was following this tutorial on Youtube to a teeth, and everything was going fine untill https://youtu.be/8t0vNu2fCCM?t=5633 when he adds siteMetadata to the gatsby-config.js .. i Have read other threads and tried to find solutions, i made sure that my packages are all up to date,  npm v 6.4.1, node v 10.15.3 & my file is name properly and located at the root of the project.  any help would be much appreciated

**Comment by pieh** [comment]
Hey, it seems like there is typo - it should be `siteMetadata` (not `sitMetadata`)

**Comment by TuBl** [comment]
My bad, i was trying to reproduce the error on my laptop quickly before i went to bed.. but still here is a screenshot from my desktop.
![a](https://user-images.githubusercontent.com/50697784/59025480-463a4400-8822-11e9-9b54-332ebe836435.PNG)

Please do note that it actually worked on my laptop after i fixed the typo... but the version of the project on my laptop is just a bit older, that should NOT make a difference though as it is just some styling that i added from the last time.

**Comment by pieh** [comment]
Field name is case sensitive - so `siteMetaData` (notice capital `D`) is still not allowed and we are looking for exactly `siteMetadata` field

**Comment by TuBl** [comment]
Thanks a lot. i guess the solution is not to learn new things at 5am and just go to bed xD
