### ISSUE TITLE
gatsby serve - H 0.0.0.0 not logging local network address

### ISSUE THREAD

**Issue by janosh** [gatsbyjs/gatsby#14745]
## Summary

Upon successful compilation, `gatsby develop -H 0.0.0.0`  logs the message

> You can now view {siteName} in the browser.
⠀
  Local:            http://0.0.0.0:8000/
  On Your Network:  http://10.248.107.170:8000/

`gatsby serve -H 0.0.0.0` should do the same. At the moment, even though it makes the site available over the local network, it doesn't give you the IP address at which to view it.

### Motivation

This is important for live-testing production builds on other devices such as phones and tablets.

**Comment by valse** [comment]
Hi,
   I can serve my production build over my lan with the command:

`gatsby serve -H 10.248.107.170`

**Comment by janosh** [comment]
Sure, but I'd like my machine's IP to be picked up automatically (hence `-H 0.0.0.0`) while still being told what it is once the production build is live.

**Comment by LekoArts** [comment]
This was fixed in the meantime.

**Comment by janosh** [comment]
@LekoArts Are you sure? I'm still not seeing it with Gatsby CLI 2.8.14, Gatsby 2.18.2.

Running

```sh
gatsby build && gatsby serve -o -H 0.0.0.0
```

for me only prints

```
success index to Algolia — 13.623 s
info Generated public/sw.js, which will
precache 5 files, totaling 685164 bytes.
The following pages will be precached:
info Done building in 84.179179892 sec
info gatsby serve running at:
info Opening browser...
```

**Comment by marcysutton** [comment]
@janosh it's been a while, are you still seeing this issue? Can you provide a test case / reproduction so we can help debug it if, so?

**Comment by janosh** [comment]
@marcysutton Yes, still seeing this. A simple way to reproduce this on my end is

```sh
gatsby new gatsby-starter-blog https://github.com/gatsbyjs/gatsby-starter-blog \
  && cd gatsby-starter-blog \
  && gatsby build \
  && gatsby serve -o -H 0.0.0.0
```

which prints

```
success Building production JavaScript and CSS bundles - 5.669s
success Rewriting compilation hashes - 0.006s
success run queries - 5.966s - 8/8 1.34/s
success Building static HTML for pages - 1.332s - 6/6 4.50/s
success Generating image thumbnails - 7.323s - 9/9 1.23/s
success onPostBuild - 0.010s
info Done building in 11.623987818 sec
info gatsby serve running at: http://0.0.0.0:9000/
info Opening browser...
```

**Comment by marcysutton** [comment]
@janosh thanks for the update! 

@LekoArts can you provide any details on what specifically was fixed months ago, so this can be debugged further? The gist of the problem, to recap, is that `gatsby develop` provides an automatic IP address for a hostname of `0.0.0.0` while `gatsby serve` does not, which is pretty inconvenient for testing production builds before deployment. More insight from a Core team perspective would be awesome!

**Comment by LekoArts** [comment]
I can't find the exact issue/PR again why I wrote that comment, but I found the PR that implemented the `develop` behavior: https://github.com/gatsbyjs/gatsby/pull/16530

So this functionality is missing in the serve command: https://github.com/gatsbyjs/gatsby/blob/99f80008b74ba7418f9a8c60a2ebdbd70ddc5dae/packages/gatsby/src/commands/serve.ts

The functionality inside develop is here:
https://github.com/gatsbyjs/gatsby/blob/99f80008b74ba7418f9a8c60a2ebdbd70ddc5dae/packages/gatsby/src/commands/develop.ts#L481-L502

So it's a matter of porting over this logic there :)
