### ISSUE TITLE
gatsby-theme-blog color mode Switch not properly saving change to localStorage

### ISSUE THREAD

**Issue by jakewies** [gatsbyjs/gatsby#15386]
## Description

Congrats GatsbyJS team on the stable release of themes! 💯 

I’ve been messing around with `gatsby-theme-blog`, and I’m noticing some strange behavior with the [`Switch` component inside of `Header`](https://github.com/gatsbyjs/gatsby/blob/master/themes/gatsby-theme-blog/src/components/header.js#L86). It doesn’t seem to be saving the current color mode in local storage.

Note, the underlying issue may have to do with [`gatsby-theme-ui`](https://github.com/system-ui/theme-ui/blob/5dcccad4eb873ea59691a23f6648755ae7c2bad9/packages/gatsby-theme-ui/src/provider.js#L14), but I’m not sure. 🤷‍♂ 

### Steps to reproduce

Bootstrap a demo with:

```
gatsby new my-themed-blog https://github.com/gatsbyjs/gatsby-starter-blog-theme

cd my-themed-blog

yarn develop 
```

Launch `localhost:8000` in your browser.

Toggle the color mode switch in the top right of the screen.

### Expected result

If you refresh the page with the color mode set to `light`, the page should reload with the color mode set to `light`.

### Actual result

When you refresh the page with the color mode set to `light`, the page reloads with the color mode reset to `dark`. 

If you open up the `Application` tab in Chrome Developer tools, and then go to localStorage for `localhost:8000`, you’ll see that the `theme-ui-color-mode` key is always being re-initialized to `dark`.

### Environment

```
  System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 11.14.0 - /usr/local/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.9.2 - ~/.npm-packages/bin/npm
  Languages:
    Python: 2.7.16 - /usr/local/bin/python
  Browsers:
    Chrome: 77.0.3833.0
    Firefox: 65.0.1
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.13.2 => 2.13.2
    gatsby-theme-blog: ^1.0.0 => 1.0.0
  npmGlobalPackages:
    gatsby-cli: 2.7.3
```

**Comment by jonniebigodes** [comment]
@akewies i've just finished creating a new project with the starter and i'm not experiencing the issue you're having. 
Issuing `gatsby-develop` and opening up `http://localhost:8000` yelds the following:
![jakewies_1](https://user-images.githubusercontent.com/22988955/60631940-2a629780-9dfa-11e9-8c0d-1c752df516be.png)

Switching the mode yelds the following:
![jakewies_2](https://user-images.githubusercontent.com/22988955/60631950-364e5980-9dfa-11e9-9ba8-4644b80b9c46.png)

Refreshing the page in either light or dark mode it's accurate. No issues there. 

If you can create a reproduction following [this](https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/) so that it can be looked at. 

Feel free to provide feedback so that we can close the issue or continue to work on it till we find a suitable solution.

**Comment by jakewies** [comment]
I created a screen recording and uploaded to gyfcat [here](https://gfycat.com/impassionedimaginaryflea). It’s really strange behavior. I can’t explain it. I watched Jason’s livestream on Twitch this morning and this wasn’t happening. I’m not sure why I’m getting the behavior.

**Comment by freiksenet** [comment]
@jakewies Do you by chance have a setting in browser that says that you "prefer dark ui"? I'm not 100% sure, but I think code here has a bug, where that overrides the stored setting. https://github.com/system-ui/theme-ui/blob/master/packages/theme-ui/src/color-modes.js#L13

**Comment by jakewies** [comment]
Hey @freiksenet ! So it looks like that’s the issue. Dark mode was added to [Chrome 73 on MacOS](https://www.howtogeek.com/405772/whats-new-in-chrome-73-arriving-march-12/). It is enabled by switching your MacOS to dark mode, which mine is on. Turning my OS to light mode fixes the issue.

> I think code here has a bug, where that overrides the stored setting. [system-ui/theme-ui:packages/theme-ui/src/color-modes.js@master#L13 ](https://github.com/system-ui/theme-ui/blob/master/packages/theme-ui/src/color-modes.js#L13)

This function indeed causes the behavior I’m seeing. It uses the `window.matchMedia` method, which returns an object with a `matches` property equal to `true` or `false`. This determines whether the user “prefers” dark mode. In MacOS this assertion is made based on the operating system setting. 

I’m not sure it’s a “bug”. The code was written with good intentions. Some people may enjoy the default dark mode setting when their operating system is set to dark mode. Personally, I would like to be able to control the website’s color mode at the website level, instead of tinkering with the operating system settings.

Pinging @jxnblk , maybe he can provide some insight.

**Comment by jxnblk** [comment]
Thanks for bringing this to our attention! The bug you've found, does look like it's related to theme-ui and how it handles the `prefers-color-scheme` media query. I've published a patch in `theme-ui@0.2.6` which attempts to address this issue. If you're able to try this out locally, that would be super helpful. The intended behavior is that when a user manually switches to a color mode, then that should take precedence over the media query

**Comment by jakewies** [comment]
Hey @jxnblk thanks for the response! I just created a new poc:

```
gatsby new my-themed-blog https://github.com/gatsbyjs/gatsby-starter-blog-theme

cd my-themed-blog
```

And verified that it is using the patched version of `theme-ui`:

```
npm view theme-ui

# shows version 0.2.6
```

I then switched my MacOS colorMode to `dark`, and ran `yarn develop`. Unfortunately the problem still persists 😞

**Comment by jxnblk** [comment]
@jakewies I've tried this locally where the starter installs `theme-ui@0.2.5`, and I am seeing the same issue you're describing in Chrome 77. If I run `rm -rf node_modules yarn.lock && yarn`, then it looks like it installs `0.2.6`, and I'm no longer seeing the issue. Here is the output of `yarn list --pattern theme-ui`:

```
yarn list v1.17.0
├─ @theme-ui/prism@0.2.5
├─ @theme-ui/typography@0.2.5
├─ gatsby-plugin-theme-ui@0.2.6
└─ theme-ui@0.2.6
```

If you could try the above, and let me know if that works, that'd be great

**Comment by jakewies** [comment]
@jxnblk Ok so that definitely fixed it. Didn’t realize I was using an older version of `theme-ui` when bootstrapping with the starter. 

So just to recap:

1. Bootstrap with the starter:

```
gatsby new my-themed-blog https://github.com/gatsbyjs/gatsby-starter-blog-theme

cd my-themed-blog
```

Testing functionality on `localhost:8000` shows improper behavior.

2. Check version of `theme-ui`:

```
❯ yarn list --pattern theme-ui
yarn list v1.15.2
├─ @theme-ui/prism@0.2.5
├─ @theme-ui/typography@0.2.5
├─ gatsby-plugin-theme-ui@0.2.5
└─ theme-ui@0.2.5
```

Verifies that the starter is using an older version of `theme-ui`.

3. Delete `node_modules` and `yarn.lock` and re-install dependencies:

```
rm -rf node_modules yarn.lock && yarn
```

4. Check version of `theme-ui` again:

```
yarn list v1.15.2
├─ @theme-ui/prism@0.2.8
├─ @theme-ui/typography@0.2.5
├─ gatsby-plugin-theme-ui@0.2.6
└─ theme-ui@0.2.6
```

Verifies that starter is _now_ using the updated version of `theme-ui`.

5. Test functionality on browser and everything works 😄

**Comment by freiksenet** [comment]
Glad that this got fixed! I'm closing this issue for now, please don't hesitate to reopen it if the problem persists.

Thank you @jxnblk and @jakewies!
