### ISSUE TITLE
I'm getting a Blank page after naming the pages in Arabic

### ISSUE THREAD

**Issue by freemh** [gatsbyjs/gatsby#15551]
## Description

If I create a page within the `src/pages` folder using Arabic language I get a blank page. All the created pages work perfectly except when I use Arabic letter for naming pages.

### Steps to reproduce

I create a new project by using `gatsby new my-project`, then I add a new page within the `src/pages` folder by using an Arabic name `صفحة.js` that contain this code:

```js
import React from "react"
import { Link } from "gatsby"

import Layout from "../components/layout"
import SEO from "../components/seo"

const TestPage = () => (
  <Layout>
    <SEO title="Test Page" />
    <h1>Test Page</h1>
    <Link to="/">Go back to the homepage</Link>
  </Layout>
)

export default TestPage
```

### Expected result

Normally I should get the content of this specific page when I visit [http://localhost:8000/صفحة/](url)

### Actual result

What actually happened is that I'm getting a Blank Page instead of the content of the page, plus the compiled HTML code looks like that:

```html
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <title data-react-helmet="true"></title>
    <link
      rel="shortcut icon"
      href="/icons/icon-48x48.png?v=008654519ce705ac7bc44303a9014606"
    />
    <link rel="manifest" href="/manifest.webmanifest" />
    <meta name="theme-color" content="#663399" />
    <link
      rel="apple-touch-icon"
      sizes="48x48"
      href="/icons/icon-48x48.png?v=008654519ce705ac7bc44303a9014606"
    />
    <link
      rel="apple-touch-icon"
      sizes="72x72"
      href="/icons/icon-72x72.png?v=008654519ce705ac7bc44303a9014606"
    />
    <link
      rel="apple-touch-icon"
      sizes="96x96"
      href="/icons/icon-96x96.png?v=008654519ce705ac7bc44303a9014606"
    />
    <link
      rel="apple-touch-icon"
      sizes="144x144"
      href="/icons/icon-144x144.png?v=008654519ce705ac7bc44303a9014606"
    />
    <link
      rel="apple-touch-icon"
      sizes="192x192"
      href="/icons/icon-192x192.png?v=008654519ce705ac7bc44303a9014606"
    />
    <link
      rel="apple-touch-icon"
      sizes="256x256"
      href="/icons/icon-256x256.png?v=008654519ce705ac7bc44303a9014606"
    />
    <link
      rel="apple-touch-icon"
      sizes="384x384"
      href="/icons/icon-384x384.png?v=008654519ce705ac7bc44303a9014606"
    />
    <link
      rel="apple-touch-icon"
      sizes="512x512"
      href="/icons/icon-512x512.png?v=008654519ce705ac7bc44303a9014606"
    />
    <script src="/socket.io/socket.io.js"></script>
    <style data-styled="" data-styled-version="4.3.2">
      /* sc-component-id: sc-bdVaJa */

      /* sc-component-id: sc-bwzfXH */

      /* sc-component-id: sc-htpNat */
    </style>
  </head>
  <body>
    <noscript id="gatsby-noscript"
      >This app works best with JavaScript enabled.</noscript
    >
    <div id="___gatsby"></div>
    <script src="/commons.js"></script>
  </body>
</html>

```
### Environment

```bash
  System:
    OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
    CPU: (1) x64 Intel(R) Xeon(R) CPU E3-1225 v3 @
3.20GHz
    Shell: 5.4.2 - /usr/bin/zsh
  Binaries:
    Node: 12.4.0 - /usr/bin/node
    Yarn: 1.16.0 - /usr/bin/yarn
    npm: 6.10.0 - /usr/bin/npm
  Languages:
    Python: 2.7.15+ - /usr/bin/python
  npmPackages:
    gatsby: ^2.13.9 => 2.13.9
    gatsby-image: ^2.2.4 => 2.2.4
    gatsby-plugin-manifest: ^2.2.1 => 2.2.1
    gatsby-plugin-offline: ^2.2.1 => 2.2.1
    gatsby-plugin-react-helmet: ^3.1.0 => 3.1.0
    gatsby-plugin-sharp: ^2.2.3 => 2.2.3
    gatsby-source-filesystem: ^2.1.2 => 2.1.2
    gatsby-transformer-sharp: ^2.2.1 => 2.2.1
  npmGlobalPackages:
    gatsby-cli: 2.7.8
```

**Comment by jonniebigodes** [comment]
@freemh to the best of my knowlege, so far Gatsby does not support non unicode . There's some work being done already. But for now if you can please rename the filenames so that you can get a successful build and content shown. 

Feel free to provide feedback.

**Comment by pantaley** [comment]
@freemh will you try with Gatsby version  2.13.1. I have the blank page issue, but with Cyrillic names.

**Comment by freemh** [comment]
> @freemh to the best of my knowlege, so far Gatsby does not support non unicode . There's some work being done already. But for now if you can please rename the filenames so that you can get a successful build and content shown.
> 
> Feel free to provide feedback.

I'm working on migrating a project from WordPress to Gatsby, so the client has already some existing pages using URLs in Arabic, so changing the name of the slugs to latin WordPress will not work in this case.
I'll try to find a hack for that.

**Comment by freemh** [comment]
> @freemh will you try with Gatsby version 2.13.1. I have the blank page issue, but with Cyrillic names.

Any language using non unicode characters is not supported as @jonniebigodes said.

**Comment by wardpeet** [comment]
have you tried gatsby@2.13.11 ?

**Comment by nhaouari** [comment]
I face the same the problem, please share with us any hack that works for you.
> > @freemh will you try with Gatsby version 2.13.1. I have the blank page issue, but with Cyrillic names.
> 
> Any language using non unicode characters is not supported as @jonniebigodes said.

**Comment by nhaouari** [comment]
the issue is fixed with the new version.

**Comment by jonniebigodes** [comment]
@nhaouari good to know that is working for you. @freemh can you check if the new version that @wardpeet mentioned works for you?

**Comment by freemh** [comment]
> @nhaouari good to know that is working for you. @freemh can you check if the new version that @wardpeet mentioned works for you?

I confirm that non unicode characters are now supported after updating to Gatsby `2.13.12`.

**Comment by freemh** [comment]
@nhaouari @wardpeet Updating to Gatsby `2.13.12` solve the problem of creating a page `صفحة.js` within the `src/pages` manually, but because I'm using `gatsby-source-wordpress` where I should create the pages programmatically from `gatsby-node.js` I still have the same blank page.

gatsby-node.js

```js
const path = require(`path`)
const slash = require(`slash`)

exports.createPages = async ({ graphql, actions }) => {
  const { createPage } = actions

  const result = await graphql(`
    {
      allWordpressWpApiMenusMenusItems(
        filter: {
          items: { elemMatch: { menu_name: { eq: "countries-menu" } } }
        }
      ) {
        edges {
          node {
            id
            items {
              object_id
              title
              menu_name
              object_slug
              menu_language
            }
          }
        }
      }
    }
  `)

  // Check for any errors
  if (result.errors) {
    throw new Error(result.errors)
  }

  // Access query results via object destructuring
  const { allWordpressWpApiMenusMenusItems } = result.data

  // Create Page pages.
  const pageTemplate = path.resolve(`./src/templates/page.js`)
  const pageTemplateAR = path.resolve(`./src/templates/page-ar.js`)

  allWordpressWpApiMenusMenusItems.edges.forEach(edge => {
    edge.node.items.forEach(item => {
      createPage({
        path:
          item.menu_language == "en"
            ? `en/${item.object_slug}`
            : item.menu_language == "ar"
            ? `ar/${decodeURI(item.object_slug)}`
            : item.menu_language == "fr"
            ? `fr/${item.object_slug}`
            : null,
        component:
          item.menu_language == "ar"
            ? slash(pageTemplateAR)
            : slash(pageTemplate),
        context: {
          wordpress_id: item.object_id,
        },
      })
    })
  })
}

```

### Summary

Creating pages manually by using non unicode characters within the `src/pages` work perfectly, but it doesn't work if I create the pages automatically, I guess that the problem is caused mainly by `gatsby-source-wordpress`

### Environment
```
  System:
    OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
    CPU: (1) x64 Intel(R) Xeon(R) CPU E3-1225 v3 @ 3.20GHz
    Shell: 5.4.2 - /usr/bin/zsh
  Binaries:
    Node: 12.4.0 - /usr/bin/node
    Yarn: 1.16.0 - /usr/bin/yarn
    npm: 6.10.0 - /usr/bin/npm
  Languages:
    Python: 2.7.15+ - /usr/bin/python
  npmPackages:
    gatsby: ^2.13.12 => 2.13.14
    gatsby-image: ^2.2.5 => 2.2.5
    gatsby-plugin-manifest: ^2.2.2 => 2.2.2
    gatsby-plugin-offline: ^2.2.2 => 2.2.2
    gatsby-plugin-react-helmet: ^3.1.1 => 3.1.1
    gatsby-plugin-sharp: ^2.2.4 => 2.2.4
    gatsby-source-filesystem: ^2.1.4 => 2.1.4
    gatsby-source-wordpress: ^3.1.6 => 3.1.6
    gatsby-transformer-sharp: ^2.2.2 => 2.2.2
  npmGlobalPackages:
    gatsby-cli: 2.7.10
```

**Comment by jamalla** [comment]
@freemh sorry i have irrelevant question please .. how do you handle the RTL in gatsby ?

**Comment by jamalla** [comment]
@freemh thanks a lot for these great resources .. nice work really .. i guess i will need to take a look at the styled component part ..

**Comment by wardpeet** [comment]
@freemh this works perfectly for me. I'm not sure what plugin you use to get the menus.

```js
exports.createPages = async ({ graphql, actions }) => {
  const { createPage } = actions

  // The “graphql” function allows us to run arbitrary
  // queries against the local Gatsby GraphQL schema. Think of
  // it like the site has a built-in database constructed
  // from the fetched data that you can run queries against.
  const result = await graphql(`
    {
      allWordpressPage {
        edges {
          node {
            id
            title
            path
            status
            template
          }
        }
      }
    }
  `)

  // Check for any errors
  if (result.errors) {
    throw new Error(result.errors)
  }

  result.data.allWordpressPage.edges.map(({ node }) => {
    createPage({
      path: decodeURI(node.path),
      component: require.resolve('./src/layout/page.js'),
      context: {
        title: node.title,
      }
    })
  })
}
```

**Comment by freemh** [comment]
> @freemh this works perfectly for me. I'm not sure what plugin you use to get the menus.
> 
> ```js
> exports.createPages = async ({ graphql, actions }) => {
>   const { createPage } = actions
> 
>   // The “graphql” function allows us to run arbitrary
>   // queries against the local Gatsby GraphQL schema. Think of
>   // it like the site has a built-in database constructed
>   // from the fetched data that you can run queries against.
>   const result = await graphql(`
>     {
>       allWordpressPage {
>         edges {
>           node {
>             id
>             title
>             path
>             status
>             template
>           }
>         }
>       }
>     }
>   `)
> 
>   // Check for any errors
>   if (result.errors) {
>     throw new Error(result.errors)
>   }
> 
>   result.data.allWordpressPage.edges.map(({ node }) => {
>     createPage({
>       path: decodeURI(node.path),
>       component: require.resolve('./src/layout/page.js'),
>       context: {
>         title: node.title,
>       }
>     })
>   })
> }
> ```

I solve the problem by including "decodeURI" on the "gatsby-node.js" and on the navigation component.
