### ISSUE TITLE
Loading chunks while a new release is deployed

### ISSUE THREAD

**Issue by antoinerousseau** [gatsbyjs/gatsby#18866]
###  Description

I think there is a structural issue with the lazy loading of page chunks.
I came across various `ChunkLoadError`s in Sentry reports, and just now it happened to me in Chrome, and it happened when I had loaded a page, then deployed a new version (via Netlify), and then tried to navigate to another page without a full page reload: the new deployed chunks have different paths, so the Gatsby Links can't find the ones it knew... throwing 404s and resulting in not being able to navigate!

### Steps to reproduce

You can easily reproduce this by deploying, going to the website, changing code & deploying again, and then trying to navigate to another page.

Otherwise, let me know and I'll setup a test website.

### Expected result

The navigation should always work.

### Actual result

Nothing happens when the visitor tries to navigate to another page.

### Possible fixes

A fix could be to fallback to normal navigation (full page reload), instead of letting the visitor on the same page without any reaction...

Now, I read on other issues that it's supposed to fail because maybe the user if offline and we can't detect it: I disagree, there is a difference between a failed [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) because of network issues) and a 404, and it can be detected in Javascript (and maybe use [NavigatorOnLine](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorOnLine/onLine) if available, too).

### Environment

```
  System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.19.0 - /usr/local/bin/yarn
    npm: 6.10.3 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Languages:
    Python: 2.7.16 - /usr/local/bin/python
  Browsers:
    Chrome: 77.0.3865.120
    Firefox: 69.0
    Safari: 13.0.2
  npmPackages:
    gatsby: ^2.15.29 => 2.15.29
    gatsby-image: ^2.2.24 => 2.2.24
    gatsby-plugin-google-analytics: ^2.1.20 => 2.1.20
    gatsby-plugin-manifest: ^2.2.20 => 2.2.20
    gatsby-plugin-netlify: ^2.1.17 => 2.1.17
    gatsby-plugin-offline: ^3.0.11 => 3.0.11
    gatsby-plugin-react-helmet: ^3.1.10 => 3.1.10
    gatsby-plugin-sharp: ^2.2.28 => 2.2.28
    gatsby-plugin-sitemap: ^2.2.16 => 2.2.16
    gatsby-plugin-styled-components: ^3.1.8 => 3.1.8
    gatsby-plugin-typescript: ^2.1.11 => 2.1.11
    gatsby-source-contentful: ^2.1.45 => 2.1.45
    gatsby-source-filesystem: ^2.1.29 => 2.1.29
    gatsby-transformer-inline-svg: ^0.0.1 => 0.0.1
    gatsby-transformer-sharp: ^2.2.20 => 2.2.20
```

### Related issues

#11194 
#2954

**Comment by thenovelnomad** [comment]
We are having a similar issue, although different cause. We are running behind an authentication proxy, and when the users session expires, navigation fails.

Is this possible related to a regression from this change?https://github.com/gatsbyjs/gatsby/pull/2996

**Comment by GooBall** [comment]
Same issue here. 

To replicate (as of v2.16.1): 
1. Clone the base Gatsby starter.
2. Run `gatsby build`.
3. Run `gatsby serve`.
4. Go to `localhost:9000/`, open network tools and hover over the "Go to page 2" link and see the network requests get made for `component---src-pages-page-2-js-[HASH].js`.
5. Go to your `./public/` folder and delete `component---src-pages-page-2-js-[HASH].js`.
6. Go back to `localhost:9000/` *do not refresh* and hover over the "Go to page 2" link. This time you will see a `404` for loading the chunk.

The above steps are what a user would experience if they were navigating a site as a new build was deployed. The user will go to click something and nothing will happen - only a page refresh will fix the issue in those cases.

I would be happy to help fix but might need pointing in the right direction as I haven't poked around in the Gatsby code to much.

**Comment by JustFly1984** [comment]
Having same issues with netlify and AWS Cloudfront.

**Comment by DevSide** [comment]
`loadComponent` is never caught, so even if we want to develop something around (refresh page, ...), it's not possible.

https://github.com/gatsbyjs/gatsby/blob/1e6954a0e8e8a661a58bc3421a3d17d8e38e766c/packages/gatsby/cache-dir/loader.js#L195

**Comment by DevSide** [comment]
`loadComponent` is never caught
https://github.com/gatsbyjs/gatsby/blob/1e6954a0e8e8a661a58bc3421a3d17d8e38e766c/packages/gatsby/cache-dir/loader.js#L195

I guess we don't even need to call `loadComponent` if the current hash compilation has changed.

Not sure navigation should take care of comparing hash
https://github.com/gatsbyjs/gatsby/blob/8938c953003e2fb488c2ae72f2eb966d0db16833/packages/gatsby/cache-dir/navigation.js#L99

The e2e test is skipped :thinking: 
https://github.com/gatsbyjs/gatsby/blob/master/e2e-tests/production-runtime/cypress/integration/compilation-hash.js#L37

**Comment by johndaskovsky** [comment]
We're seeing this same issue as well.

**Comment by manutdkid77** [comment]
Looks like I'm facing a similar issue as this as well, running gatsby 2.15.33 and hosted on Netlify.

Following are the logs in the console from Firefox:

```
Error: Loading CSS chunk 1 failed.
(/styles.372f89c282666a74bcb5.css) webpack-runtime-a06d2033887a729e229a.js:1:1913
Source map error: Error: request failed with status 404
Resource URL: https://www.websitename.com/webpack-runtime-a06d2033887a729e229a.js
Source Map URL: webpack-runtime-a06d2033887a729e229a.js.map
```

**Comment by JustFly1984** [comment]
This is major bug, which contradicts the main goal of CI/CD flow.

**Comment by editkid** [comment]
Can anyone identify a known working version of Gatsby that doesn't exhibit this bug? Rolling back to `v2.15.37` as suggested by @jjang16 didn't seem to work for us.

Or rather is this an issue with one of Gatsby's dependencies?

Sorry, I don't have much more to contribute at this stage apart from questions.

**Comment by ryami333** [comment]
Strange that the tests were disabled because they were failing, isn't that the idea of tests?? 😅I'd have thought that a regression which breaks a test (disabled or not) would necessitate a pretty hasty hotfix! @pieh I see you're assigned to this one - do you have the context to address it or do you need some help getting to the bottom of it?

**Comment by JustFly1984** [comment]
@pieh @ryami333 @editkid I can only guess at this point, but I think it could be issue with `gatsby-plugin-offline`

**Comment by johndaskovsky** [comment]
@JustFly1984 we have the issue but don't have `gatsby-plugin-offline` enabled

**Comment by JustFly1984** [comment]
@johndaskovsky thank you for clarification, this is even worst than I thought.

**Comment by ryami333** [comment]
Yeah no `gatsby-plugin-offline` for us either.

**Comment by JustFly1984** [comment]
@sever1an can you check if you have same issue?

**Comment by mitchellbutler** [comment]
We're running an e-commerce site with Gatsby on Netlify and have noticed a number of these `ChunkLoadError` logs in Sentry whenever we deploy. I've tested this with the official Gatsby starter and it seems to have the same behavior.

I wonder if more people are having this issue and simply aren't noticing because they aren't monitoring client errors or don't have a lot of active sessions during deployment. For now, we're watching real-time sessions and deploying at odd hours to avoid the issue but it would be great not to have to worry about it.

## Minimal Steps to Reproduce

**I've uploaded a screen recording of the process [here](https://vimeo.com/379160840)**.

1. Create a new gatsby site e.g., `gatsby new gatsby-issue-18866`
2. Publish it to Netlify
3. Navigate to the Netlify link, but **do not hover over or click the "Go to page 2" link**
4. Keep the window open and deploy some changes to `./src/pages/page-2`
5. Wait for Netlify to process the build.
6. Now hover or click the "Go to page 2" link

## Result

The link does not function and throws a `ChunkLoadError` on each hover and click.

The output looks similar to this:

```
webpack-runtime-fcfa123cba71df322157.js:1 GET https://cocky-jackson-37ee43.netlify.com/component---src-pages-page-2-js-9091273db8b77923343d.js net::ERR_ABORTED 404
webpack-runtime-fcfa123cba71df322157.js:1 Uncaught (in promise) ChunkLoadError: Loading chunk 5 failed.
(error: https://cocky-jackson-37ee43.netlify.com/component---src-pages-page-2-js-9091273db8b77923343d.js)
    at Function.u.e (https://cocky-jackson-37ee43.netlify.com/webpack-runtime-fcfa123cba71df322157.js:1:2172)
    at Object.component---src-pages-page-2-js (https://cocky-jackson-37ee43.netlify.com/app-41cbafd5610a9d24601a.js:1:87364)
    at r.loadComponent (https://cocky-jackson-37ee43.netlify.com/app-41cbafd5610a9d24601a.js:1:78493)
    at https://cocky-jackson-37ee43.netlify.com/app-41cbafd5610a9d24601a.js:1:76405
```

**Comment by editkid** [comment]
> I wonder if more people are having this issue and simply aren't noticing because they aren't monitoring client errors.

I think so, yes.

We've noticed `ChunkLoadError` happen many days after a deploy, likely due to people leaving our website open in their browser for prolonged periods. It's especially problematic when we deploy backwards-incompatible changes to our server-side API and need all our clients to refresh.

**Comment by christerwpersson** [comment]
We are also running an e-commerce with Gatsby on Netlify (which is a lovely experience overall i must say!) but we too, have been running into a bunch of not so nice experiences for customers who has been in the middle of the checkout flow, as it relies on the user being navigated between different pages, which breaks when we do a new deploy (and was not built with this issue in mind)

Since there are users in the checkout flow basically all the time, there is no 'safe' window where we can do a deploy without putting ourselves in a really bad spot. We've basically had to revert to avoid doing deploys as often, which is obviously a not so nice experience.

I'm not sure this is all on Gatsby though, e.g. if Netlify would avoid deleting all old files (ie. the chunks would still be there) on new deploys this wouldn't be an issue i believe? But it feels like Gatsby should have a safe fallback for this?

**Comment by JustFly1984** [comment]
We have same issues both on netlify and AWS Cloudfront/S3.

**Comment by GooBall** [comment]
The only fix I have been able to implement has been to remove all use of gatsby-link and just use anchor tags. Full page reloads are not nice but nothing can be done until this is fixed.

**Comment by JustFly1984** [comment]
@GooBall in our case page reload is not acceptable, cos we have authenticated state. and Safari drops cookies for cross-domain requests.

**Comment by editkid** [comment]
Our site's design relies heavily on page transitions hence removing `gatsby-link` is not an option for us either.

**Comment by smbkr** [comment]
I've done a bit of investigation into this myself as it's causing a lot of alerts for us when we deploy, due to active user on our website, and sometimes days later, which I assume is users who had opened the site before a deploy and continued to use it some time later like @editkid describes.

Here's the PR that I believe introduced this bug: https://github.com/gatsbyjs/gatsby/pull/16686

If you look at the CI logs for this PR, the disabled test in `e2e-tests/production-runtime/cypress/integration/compilation-hash.js#L37` that @DevSide has pointed out was skipped, so I guess this bug was missed.

The most recent change to `packages/gatsby/cache-dir/loader.js` prior to the one from the PR links was run against the now disabled test, and passed.

Unfortunately I don't know enough about this side of WebPack or Gatsby to be of much further use, but hopefully this is of some help @pieh

**Comment by ryami333** [comment]
Sorry to "at" you @KyleAMathews, but there hasn't been any comment or activity from @pieh on this since it was assigned to him a couple of months ago. Is there someone else who might be able to check this out? There seems to be a reasonable number of people affected by this, and it's easily and reliably reproducible with the latest version of Gatsby (including any given "starter").

**Comment by JustFly1984** [comment]
@KyleAMathews  please fix this issue

**Comment by sidharthachatterjee** [comment]
Apologies for the silence here, folks. We're currently [on holiday](https://github.com/gatsbyjs/gatsby/issues/20247#issue-541092051) but will be sure to take a look at this once we're back.

**Comment by JustFly1984** [comment]
@DSchau This issue actually impacting everybody. It's just not everybody noticing.

**Comment by jaredsilver** [comment]
FWIW, we just upgraded from `2.17.7` to `2.18.17`, and now we're seeing a deluge of errors like this in Sentry. We do not use `gatsby-link`.

**Comment by DevSide** [comment]
It's not as easy as it seems to be. 

Depending on the volume of pages, updates can take a while and Gatsby doesn't know if all files necessary were uploaded. Actually, it can't predict the right moment to reload for now.
Also, some people may want to reload when navigation occurred but others would prefer a user button to manually do it.

A likely solution would be to create a custom hook like "onLoadPageFailed" which give the maximum amount of information to let the dev do what they want.

**Comment by JustFly1984** [comment]
There is clearly an error, and any errors can be handled with fallback. 

I would rather redirect user to maintenance page while trying to navigate to requested page several times, and make a page reload after 5 unsuccessful attempts. Would be useful if Gatsby.js could provide similar to 404 page functionality for maintenance page with internationalization support and createPages API support. currently it is a bit hacky to provide internationalization (react-intl) support for 404 page.

Also I'm worried there could be issues for client-side only routes.

**Comment by JustFly1984** [comment]
One more thing: currently we are using AWS Cloudfront, and deploy consist of 5 steps before error: 

- clear /dist dir
- build to /dist dir
- sync /dist dir with s3 and deleting outdated files from s3
- creation of invalidation fro CloudFront 
- invalidation take couple minutes to update cache worldwide on edge locations.

- at this point all users using website starting getting errors on navigation, which we track in Sentry

in Cloudfront case there is definitely all files updated, and we could reload page on navigation without page preload to update offline service-worker cache and UI. I could bet the same concerns netlify, cos there is docker container swap happens on build process.

Please correct me if I'm wrong.

**Comment by jperasmus** [comment]
We've seen similar issues on a non-Gatsby app before when using the `skipWaiting` option for service workers. With `skipWaiting` the new service worker installs and become active straight away, which clears out old asset caches. If the already loaded page references one of these assets that are now deleted, it will error. Afaik, the Gatsby offline plugin uses `skipWaiting` by default.

The way we "fixed" it was by not using `skipWaiting` and rather show the user an "Updates Available" notification that prompts them to refresh for the changes to take effect. A great fix would be if the already loaded code could hot replace any old chunk references with new ones, but that sounds like a rabbit hole no-one wants to go down.

**Comment by antoinerousseau** [comment]
Thanks, although I'm not using any service workers and it still happens.

**Comment by JohanBengtsson** [comment]
We're also having big problems with this. I can see that this issue is in the "Prioritized" column in the Roadmap, but I'm not sure that this means. Does anyone know whether it's something that might be adressed in the near future?

**Comment by josepjaume** [comment]
What about just resorting to full page reload when there's an error within navigation? It would solve most issues. It's probably most cases of chunk load errors.

**Comment by antoinerousseau** [comment]
@josepjaume yes, it's what I proposed in the issue description, we should fallback to full page reload

**Comment by aychtang** [comment]
This seems to be another reason people are lead to attempting the fixes detailed in https://github.com/gatsbyjs/gatsby/issues/15080 and is related to my last comment in that thread

**Comment by pieh** [comment]
Just a note - there is work being done on it in https://github.com/gatsbyjs/gatsby/pull/18051 (the description of the PR is outdated tho as I shifted the direction of the PR and didn't update it). and I needed to make changes to proposed e2e changes there to assert that user IS able to navigate to a page even if some resources fail to load), but runtime is pretty important thing and we need to be careful about making changes in navigation code so it takes time and lot of manual testing (on top of those e2e tests that are there now).

I had call today with @wardpeet and @blainekasten about this issue and the work in progress that I did so far. There were valid concerns raised about some of changes that I made. There will be more changes coming there (including just some code readability stuff so it would be easier to iterate on that in the future)

**Comment by senorgeno** [comment]
So it seems the best solution, for now, is to do a page reload when the error is thrown. 

Does anyone have a suggestion about how best to do this? I am trying to use an Error Boundary in gatsby-browser that wraps the app. However, in trying to simulate the issue locally it isn't actually being caught by this.

**Comment by pieh** [comment]
I just want to mention we just published new version of gatsby (`gatsby@2.19.41`) with bit improved loader resilience (PR that I mentioned - https://github.com/gatsbyjs/gatsby/pull/18051 was merged). It will not fix all the issues, but large chunk of them are handled.

We also re-added some e2e tests to verify navigation correctness in bunch of scenarios when resources fail to load (for whatever reason - network issues, adblockers, mid-deploy scenarios)

**Comment by jperasmus** [comment]
"large **chunk** of them" 😂

**Comment by JustFly1984** [comment]
Currently I can’t test 41 version, cos it contains 2 typescript errors and fails on test

**Comment by willm** [comment]
@pieh We upgraded to 2.19.41 yesterday, but are still getting ChunkLoadErrors quite frequently. If we can provide more information, please let me know.

**Comment by stuckj** [comment]
We're also hitting this on our site using gatsby and hosted in Netlify.

That said. This looks like an age-old problem. I've seen this problem before with many other systems and I'm reluctant to call this a gatsby issue. Basic website versioning says you change hashes when the file changes so it busts the client cache.

If your website is navigating via JS (like gatsby sites do) then you either need to signal to the running JS code that there's a new version available so it can either force reload or do something "smarter" to load the new page chunks.

The usual way I've solved this in the past was to leave the last version up for some time (few days was sufficient...though storage for static sites is generally cheap enough that you could do months if you wanted). That reduced the possibility that anyone still has a running JS page with the old code references. With a straight S3 hosted site this is relatively easy to do in a CI/CD system by setting expirations for the older pages. That's outside of gatsby's purview though.

I kinda think of this more of a Netlify issue. But...if there's a solution that can be done via Gatsby, I'm all for it too since I'd prefer we didn't have users hitting this either. :)

**Comment by pauleveritt** [comment]
I was going to add a "Me too" comment. I upgraded to the latest of everything, hoping a transient dead-page error was fixed based on recent changes. Things to worse: nearly every page would display, then disappear.

Turns out it was an AWS error, swallowed-up by my CI: `An error occurred (InvalidAccessKeyId) when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.`

One put of one `.js` and my site silently broke. Yikes.

So the cause is found, but goodness, I thought Gatsby was cool because it worked without JS. Ironically, my site would have worked with JS disabled, but was broken with JS.

**Comment by stuckj** [comment]
That also doesn't sound like a gatsby issue since gatsby doesn't deal with AWS at all. :)

**Comment by pauleveritt** [comment]
@stuckj Correct, I was about to blame Gatsby but then realized it was a buried AWS warning. Thought I'd share that as FYI for others.

That said, an SSG which loads the generated HTML, then erases it because a .js couldn't be found, possibly has a flaw in the strategy.

**Comment by JustFly1984** [comment]
not stale!

**Comment by mitchellbutler** [comment]
It's been eight months since this issue was opened and I'm curious if anyone's found a good way to work around it?

I can see Netlify is claiming that "[More than half of all Gatsby sites are deployed on Netlify.](https://www.netlify.com/with/gatsby/)". As far as I can tell there's no way to force Netlify to maintain cache from previous builds. Does that mean that most production Gatsby sites break all active and recent sessions on deploy?

**Comment by JustFly1984** [comment]
@wardpeet @pieh is there any progress on this issue?

**Comment by JustFly1984** [comment]
@wardpeet @pieh please pay attention to this issue

**Comment by andyhmltn** [comment]
Also seeing this error

**Comment by theskillwithin** [comment]
Get this issue a lot

**Comment by maciek-bejamas** [comment]
In my team, we've got used to clean the cache after each deployment.

**Comment by tlgimenes** [comment]
I'm also seeing loads and loads of this error in my sentry dashboard

**Comment by lloydh** [comment]
Still seeing this.

**Comment by KyleAMathews** [comment]
@lloydh generally this is related to your caching headers — you can check if your hosting is setup correctly by running `npx check-gatsby-caching https://url-of-your-gatsby-site.com` — https://www.npmjs.com/package/check-gatsby-caching

**Comment by lloydh** [comment]
@KyleAMathews thanks for the tip.

Fortunately/unfortunately in my case the headers check all came back as correct. This site is running on Netlify, in case there's a trend.

```
HTML
https://www.visakingsglobal.com
✅ headers are correct!

app-data.json
https://www.visakingsglobal.com/page-data/app-data.json
✅ headers are correct!

Page Data
https://www.visakingsglobal.com/page-data/index/page-data.json
✅ headers are correct!

JavaScript and CSS
https://www.visakingsglobal.com/webpack-runtime-8bd35c20cf1bd38cfd5a.js
✅ headers are correct!
```

**Comment by theskillwithin** [comment]
on Netlify for me the last one failed:
```
JavaScript and CSS
https://*redacted*.com/webpack-runtime-8458c4b71bd3c017ae4d.js
❌

- Expected
+ Received

  Object {
-   "immutable": true,
-   "max-age": 31536000,
+   "max-age": 0,
+   "must-revalidate": true,
    "public": true,
  }
```

**Comment by mitchellbutler** [comment]
I'm fairly sure this is not a caching issue. The bundles referenced in the HTML will no longer exist if your site is rebuilt while someone is using it. It doesn't matter how they are cached. It's _sort of_ a Netlify issue since they're purging the files from the last build when a new one is deployed. Ideally, though, Gatsby would have a strategy for failing gracefully when the bundles you're pointing to no longer exist.

**Comment by stuckj** [comment]
I mentioned this further up, but I see this completely as a Netlify issue. We also see this on our site on Netlify. I've run into this on other web projects (completely different stacks) and the problem is simply not immediately dumping your old builds when your new build deploys. For comparison, this would be like expecting software running on your computer to gracefully handle upgrading to a new version while the software is running. That's a pretty tall ask. If the code is already in the user's browser and they navigate (via JS) to a page that requests a resource that no longer exists (since the running code is for an old build), it's pretty tough to fallback to something sensible. I mean...you could do a force refresh on the page, but I can think of all sorts of cases where that would be equally terrible. Also, it would have to distinguish between a resource missing due to a new build being pushed vs, e.g., a temporary issue (bad network connection...link down, etc etc).

In other systems I've worked on you don't immediately remove the old builds. Heck, in the last place I was at we left ALL old builds up since it was pennies for storage of them. But...more reasonably, have a timeout for when builds are removed (say 24 hrs for an abundance of caution).

**Comment by mitchellbutler** [comment]
> For comparison, this would be like expecting software running on your computer to gracefully handle upgrading to a new version while the software is running.

I like this analogy, but I wonder if this bug is more like software that tends to break during a "background" update?

Unfortunately with e-commerce, it's not uncommon to have tens of thousands of dollars of product sitting in the carts of active sessions during peak sales periods. Deploying at the wrong time in a way that might break the path to checkout becomes a very expensive decision.

I agree that persisting old builds is an ideal fix. It changes some of the fundamental assumptions that CI/hosting platforms make though, and I can imagine how it might make some features (e.g., rollback) more complex.

I've also seen mention of  reverting a `gatsby-router` link to a traditional anchor link when the bundle fails, or providing an API for handling this failure state rather than having it happen silently (e.g., a hook from `gatsby-router` so that we could produce a banner with a message like, "we've detected network issues [Reload this Page?]"). It seems like these are both paths that could be taken regardless of the work that has to be done on build persistence.

To make progress with the CI/hosting services, maybe someone should close this with a "won't fix" label. That way we can at least move the issue to our service providers and it can be referenced as a platform decision. Labels like `status: confirmed`, `type: bug`, and `topic: webpack/babel` are keeping the issue in limbo since it seems like Gatsby recognizes this as a platform issue.

**Comment by aaronadamsCA** [comment]
Gatsby v3 on Gatsby Cloud also has this issue, I've got the Sentry alerts to prove it. 🙃

Given this is now a problem on the first-party hosting solution, maybe the core team could work with the cloud team to decide where and how this should be resolved; and then that could guide other platforms like Netlify?

Unfortunately I don't have a stack trace, but if this is indeed happening during preload and navigate events, could you just catch `ChunkLoadError`, ignore it on hover, and fall back to `window.navigate` on click?

**Comment by jdortegar** [comment]
same issue here with Gatsby v3 deployed in Netlify and Cloudfront

**Comment by mustofa-binary** [comment]
same issue here with gatsby deployed in S3

**Comment by favoyang** [comment]
From the VuePress community, exactly the same issue solved by a tiny plugin - https://github.com/cwaring/vuepress-plugin-chunkload-redirect/blob/main/clientRootMixin.js - hooks the `unhandledrejection` event and then performs a full reload.

Someone wants to create a simliar plugin for gatsbyjs.

**Comment by mmclafferty** [comment]
This is happening thousands of times a week for me with the new gatsby-plugin-image since it does dynamic imports on `intersection-observer` and `lazy-hydate` causing them to  be bundle split. Those assets do exist, so no idea why they randomly fail to load.

**Comment by philschonholzer** [comment]
Also getting this a lot in sentry and have also noticed this myself after deployment. The plugin mentioned by @favoyang sounds like the right approach.

**Comment by KyleAMathews** [comment]
To do something similar to that vuepress plugin in your Gatsby site, you could trying adding something like the following in your site's `gatsby-browser.js`:

```js
let nextRoute = ``

exports.onPreRouteUpdate = ({ location }) => {
  nextRoute = location.pathname
}

window.addEventListener("unhandledrejection", event => {
   if (/loading chunk \d* failed./i.test(event.reason)) {
        if (nextRoute) {
          window.location.pathname = nextRoute
       }
    }
});
```

If this solves the issue — it'd either be a great plugin or quite probably be something we would add directly in the framework. I would love if someone who regularly sees this problem could test out the fix and report back!

**Comment by philschonholzer** [comment]
>  I would love if someone who regularly sees this problem could test out the fix and report back!

Great! I just pushed this for our page. I'll report back if this works.

**Comment by ceiphr** [comment]
> I would love if someone who regularly sees this problem could test out the fix and report back!

Thank you for this! I believe it is working for me. I refactored a few pages on my site and when I clicked a `gatsby-router` link after deployment, the page refreshed instead of causing a navigation failure. 

The only caveat is that errors are still logged by Sentry, so I added `ignoreErrors: ["ChunkLoadError"]` to my `gatsby-config.js`. It's probably not the best approach to ignore an error, but in this context it seems like your fix is working.

**Comment by antoinerousseau** [comment]
Where is the failing Promise anyway? Can we not perform the fallback in its `.catch()`?

**Comment by KyleAMathews** [comment]
I don't _think_ we can catch the error because it's happening inside webpack. So `unhandledrejection` is our only bet here.

**Comment by AlexanderBich** [comment]
Has anyone already tested the proposed workound?
Itt would be great to see some feedback
@philschonholzer - any updates on your side?

**Comment by philschonholzer** [comment]
@AlexanderBich It does just what it should. Since we added the workaround to `gatsby-browser.js` the page refreshes automatically after a new deployment and the error disappeared from sentry.io.

@KyleAMathews This should really be part of every Gatsby installation.

**Comment by lloydh** [comment]
> @AlexanderBich It does just what it should. Since we added the workaround to `gatsby-browser.js` the page refreshes automatically after a new deployment and the error disappeared from sentry.io.
> 
> @KyleAMathews This should really be part of every Gatsby installation.

Seconded

**Comment by stuckj** [comment]
Yep, it's working for us as well. If this gets added in some default way to gatsby, please update this thread so we can remove our patch. :)

**Comment by AlexanderBich** [comment]
> This is happening thousands of times a week for me with the new gatsby-plugin-image since it does dynamic imports on `intersection-observer` and `lazy-hydate` causing them to be bundle split. Those assets do exist, so no idea why they randomly fail to load. However, my issue is unrelated to the topic which is geared toward while its being deployed.

gatsby-plugin-image still throws chunk error even after fix.
But this maybe due to a different issue

**Comment by mmclafferty** [comment]
> > This is happening thousands of times a week for me with the new gatsby-plugin-image since it does dynamic imports on `intersection-observer` and `lazy-hydate` causing them to be bundle split. Those assets do exist, so no idea why they randomly fail to load. However, my issue is unrelated to the topic which is geared toward while its being deployed.
> 
> gatsby-plugin-image still throws chunk errors even after fix.
> But this is maybe due to a different issue and even possibly with service worker of `gatsby-plugin-offline` and presumably can be fixed by disabling `skipWaiting` option @mmclafferty

I was able to work around this issue by adding this to my webpack config. It forces their dynamic imports into the main app bundle.

```
  if (stage === `build-javascript`) {
    config.optimization.splitChunks.cacheGroups.images = {
      name: 'app',
      test(module) {
        return /node_modules[/\\]gatsby-plugin-image[/\\]/.test(
          module.identifier()
        );
      },
    };
  }
  ```

**Comment by ryami333** [comment]
I think this discussion about `gatsby-plugin-image` and `gatsby-plugin-offline` is becoming a little bit distracting. As I mentioned above, this issue is _easily and reliably reproducible with the latest version of Gatsby (including any given "starter")_. Any specific problems that arise from the inclusion of those plugins should be raised in separate issues. We're already starved for the attention of core developers here, so we should be mindful not just to create more noise for them!

**Comment by laustdeleuran** [comment]
We're running into this as well on Netlify + Gatsby. Would love to hear from the Gatsby folks if there's any plan to bridge this?

**Comment by Elyx0** [comment]
@KyleAMathews What should be done when the Javascript and CSS step of `npx check-gatsby-caching` expects something different. (Gatsby 3.1.2+Netlify), getting Chunks errors day and night.
```
HTML
https://app.charged.fi
✅ headers are correct!


app-data.json
https://app.charged.fi/page-data/app-data.json
✅ headers are correct!


Page Data
https://app.charged.fi/page-data/index/page-data.json
✅ headers are correct!


JavaScript and CSS
https://app.charged.fi/webpack-runtime.js
❌

- Expected
+ Received

  Object {
-   "immutable": true,
-   "max-age": 31536000,
+   "max-age": 0,
+   "must-revalidate": true,
    "public": true,
  }
```

**Comment by KyleAMathews** [comment]
@Elyx0 — the last error is fine — immutable is preferred as it's faster but must-revalidate is perfectly safe. This should ideally be a warning not an error — the tool isn't smart enough to differentiate between ideal and less-than-ideal

One thing that could help is adding https://github.com/gatsbyjs/gatsby/issues/18866#issuecomment-844449917 to your gatsby-browser.js

**Comment by KyleAMathews** [comment]
BTW, I opened up a PR to add my code snippet to the framework https://github.com/gatsbyjs/gatsby/pull/33032

**Comment by seanflahertyT4** [comment]
It would be awesome to backport this to gatsby 3... I know its not supported anymore but having this bug in the last release of it is quite frustrating for devs who are stuck on gatsby 3 for production sites.  https://stackoverflow.com/questions/71506592/gatsby-development-server-stops-on-every-syntax-error
