### ISSUE TITLE
How to stop Gatsby from redirecting '/index.html' to '/'?

### ISSUE THREAD

**Issue by drake-smith** [gatsbyjs/gatsby#20203]
I have a one page site that has to be served at website.com/index.html (not website.com/). I'm finding that when I visit website.com/index.html on my deployed site, the site url will redirect to website.com/ after load. I do not see a redirect happening in my browser Network tab either. And I've tried several different hosting platforms like AWS, Netlify.

How do I stop this and leave it at website.com/index.html?

**Comment by pieh** [comment]
We will update url to canonical path to a page. 

If you are using automatic pages generation by using `src/pages/index.js` - this will set canonical path to `/`.

You can change in few ways:
 - modify path from automaticly created index page - by adding following snippet to `gatsby-node.js` file:

```js
exports.onCreatePage = ({ page, actions }) => {
  const { createPage, deletePage } = actions
  
  if (page.path === `/`) {
    // remove old one
    deletePage(page)
    // and create new one with modified path
    createPage({
      ...page,
      path: `/index.html`
    })
  }
}
```

- instead of using `src/pages/index.js` for automatic page creation - use other directory than `pages` - i.e. `src/templates/index.js` and  - in `gatsby-node.js, programatically tell gatsby to create `/index.html` page using that template:

```js
exports.createPages = ({ actions }) => {
  actions.createPage({
    path: `/index.html`,
    component: require.resolve(`./src/templates/index.js`)
  })
}
```

Pick one of those, and hopefully that should solve the issue

**Comment by drake-smith** [comment]
Hi! Thanks for the response @pieh. 

Here is some more context on my situation:

In gatsby-node, I dynamically create a homepage with path '/index.html' (aka using the approach 2 you suggested).

```
createPage({
        path: process.env.NODE_ENV === 'production' ? `/index.html` : '/',
        component: pageTemplate,
        context: {
          slug: node.slug,
        },
});
```

I run `gatsby serve` and view my site at localhost:9000/index.html.

The HTML + CSS renders but I get errors trying to get `page-data.json`. I get a 404 at URL http://localhost:9000/page-data/index/page-data.json.

Below is a screenshot of my `public` build directory.

<img width="281" alt="Screen Shot 2019-12-18 at 4 00 18 PM" src="https://user-images.githubusercontent.com/18299801/71133466-8bff9e00-21af-11ea-8818-52fea0722a6c.png">

I see that because I set the page path to 'index.html', that page-data folder is called `index.html`. But the URL request for the file in that folder only references /index/, no /index.html'. 

Any idea on what I could do?

**Comment by drake-smith** [comment]
An update - I believe updating my canonical url to a URL with '/index.html' has resolved the redirect. However, it still does not work in production and I get the same 404 errors in regards to `page-data.json` from my previous comment.

**Comment by pieh** [comment]
Yeah, you are right. This is not working neither in develop (can't even navigate there) or build (wrong page-data url). For now I'll mark this issue as a bug, but will need to open new one with clear bug description and minimal reproduction (can use https://github.com/pieh/dot-html-pages-are-broken for that)

**Comment by drake-smith** [comment]
I will open a new bug report for this issue.

**Comment by joewood** [comment]
Is there a new issue for this? Any updated?

**Comment by drake-smith** [comment]
I've opened up a bug report that is more fleshed out. https://github.com/gatsbyjs/gatsby/issues/21252

**Comment by LekoArts** [comment]
Let's close this in favor of https://github.com/gatsbyjs/gatsby/issues/21252 then.
