### ISSUE TITLE
styled-components v5  global styles is not inlined

### ISSUE THREAD

**Issue by EugeneDraitsev** [gatsbyjs/gatsby#20594]
## Description

Looks like styled-components v5 global styles injection is not working with gatsby 2.18.12 and gatsby-plugin-styled-components 3.1.17.

I have same gatsby-browser and gatsby-ssr
```jsx
import React from "react"

import { createGlobalStyle } from "styled-components"

const GlobalStyle = createGlobalStyle`
  body {
    background: slategray;
  }
`

// eslint-disable-next-line react/prop-types
export const wrapRootElement = ({ element }) => (
  // eslint-disable-next-line react/jsx-filename-extension
  <>
    <GlobalStyle />
    {element}
  </>
)
```

and simple index.js page
```jsx
import React from "react"

export default () => <div>Hello world!</div>
```

index.html After build with styled-components 5.0.0 
<img width="840" alt="image" src="https://user-images.githubusercontent.com/16540432/72359352-6b632f00-36ee-11ea-998b-688c40938274.png">

index.html After build with styled-components 4.4.1 
<img width="725" alt="image" src="https://user-images.githubusercontent.com/16540432/72359244-3bb42700-36ee-11ea-8f22-cb1bd331443f.png">

Also I noticed that moving `GlobalStyle` from gatsby-browser and gatsby-ssr to index page fixes this behavior, but unfortunately it's not fit in my case

### Steps to reproduce

1. Follow this instructions https://www.gatsbyjs.org/docs/styled-components/ and move GlobalStyles to gatsby-browser and gatsby-ssr. (or just clone this repo: https://github.com/EugeneDraitsev/gatsby-styled-components-5)
2. Run yarn build
3. Check public/index.html

Repo: https://github.com/EugeneDraitsev/gatsby-styled-components-5
Demo v5: https://priceless-mayer-7a8244.netlify.com/
Demo v4: https://deploy-preview-1--priceless-mayer-7a8244.netlify.com/
(Try to update pages in demos to see the difference) 

### Expected result

Global styles should be injected

### Actual result

Global are not injected

### Environment
```
  System:
    OS: macOS 10.15.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.1 - ~/.nvm/versions/node/v12.13.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/local/bin/python
  Browsers:
    Chrome: 79.0.3945.117
    Safari: 13.0.3
  npmPackages:
    gatsby: ^2.18.12 => 2.18.12 
    gatsby-plugin-styled-components: ^3.1.17 => 3.1.17 
```

**Comment by pieh** [comment]
If you change `wrapRootElement` in both gatsby-ssr and gatsby-browser to `wrapPageElement` it seems to fix that (to at least unblock you).

I'll try to dig up what changed in styled-components v4 <-> v5 that it stopped working

**Comment by pieh** [comment]
I suspect that when you use `wrapRootElement` it position your `<GlobalStyles>` above `<StyleSheetManager>` (provided by `gatsby-plugin-styled-components`) in component tree, and therefore we can't extract it (this seems to change in `styled-components` as in v4 it was working).

Where did you pick up using `wrapRootElement` to handle global styles? In our docs we recommend using `gatsby-plugin-layout` (which under the hood uses `wrapPageElement`) - https://www.gatsbyjs.org/docs/styled-components/#creating-global-styles

**Comment by EugeneDraitsev** [comment]
@pieh thanks for quick response! Global styles are injected with `wrapPageElement `, but looks like styled-components v5 have even more weird issue. So with `wrapPageElement ` I have this style tag:

![image](https://user-images.githubusercontent.com/16540432/72364417-c6008900-36f6-11ea-8d1d-489fafc25598.png)

Looks like it finally should work, but no!:

v5: 
![v5](https://user-images.githubusercontent.com/16540432/72365344-555a6c00-36f8-11ea-99e2-f6e36fd90750.gif)


v4: 
![v4](https://user-images.githubusercontent.com/16540432/72365342-5390a880-36f8-11ea-93f9-da39c35d2a56.gif)

If I remove `data-styled` and `data-styled-version` attribute, then it works without blinking.
I'll try to use `gatsby-plugin-layout` a bit later

**Comment by pieh** [comment]
Interesting. I can't seem to reproduce the flashing part with v5 and using `wrapPageElement`. I do get exactly same html output (with "empty" data-styled attribute and "styles" for `data-styled.g1[id="sc-global-fYJafS1"]`

If you are using `wraPageElement` there shouldn't be any difference with `gatsby-plugin-layout` (that's just convenience wrapper around that API to not have to use both `gatsby-ssr` and `gatsby-browser`)

**Comment by pieh** [comment]
This is very unlikely, but: what are you using to serve your files? The 5000 port would suggest not using `gatsby serve` micro server (or maybe using it with explicit port flag). Maybe server thinks you have to html request cached and using that? (probably not the case, but I'm bit out of ideas why I don't see this flashing)

**Comment by EugeneDraitsev** [comment]
I use https://www.npmjs.com/package/serve to serve build locally and looks like it can be a reason of blinking. I deployed `wrapPageElement` version to Netlify and it works fine:

Demo v5 `wrapPageElement` : https://5e1e06113026ba00082b4e11--priceless-mayer-7a8244.netlify.com/

So look like it doesn't work only with `wrapRootElement ` and sometimes with serve)

**Comment by pieh** [comment]
I feel like issue is resolved at this point, documentation points to using `wrapPageElement` (indirectly) for this case, so there are no action items we can generate from this?

Shall we close this?

**Comment by EugeneDraitsev** [comment]
Ok, I don't have any problems with `wrapPageElement`, let's close it

**Comment by jamesgrubb** [comment]
Changing to wrapPageElement fixed the issue for me

**Comment by senorgeno** [comment]
Hey, @pieh I have a large gatsby site I am in the process of upgrading to styled-components v5. I too am having this issue, however, when I change to wrapPageElement from wrapRootElement I still get the same problem in the original issue. 

Any other suggestions? Could it be another gatsby plugin using wrapRootElement affecting things?

**Comment by Kallirroi** [comment]
I'm also running into this issue when using `gatsby-plugin-breakpoints`. It materializes as a momentary flicker of CSS that should apply to mobile, while I am on desktop. It lasts around a second and then goes away. 

I am using Apollo which I suspect might be introducing complexities in how `gatsby-ssr` and `gatsby-browser` talk to each other. 

Here is what I have: 

**apollo/wrap-page-element.js**
```
import React from 'react';
import { ApolloProvider, ApolloClient, createHttpLink, InMemoryCache } from '@apollo/client';
import fetch from "isomorphic-fetch"

const httpLink = createHttpLink({
    uri: process.env.NODE_ENV === `development`
        ? `http://localhost:8888/test/graphql`
        : `https://importiv.wordsinspace.net/graphql`
});

const client = new ApolloClient({
    fetch,
    link: httpLink,
    cache: new InMemoryCache(),
});

export const wrapPageElement = ({ element }) => (
  <ApolloProvider client={client}>{element}</ApolloProvider>
);
```

**gatsby-ssr.js**
`export { wrapPageElement } from './src/apollo/wrap-page-element';`

**gatsby-browser.js**
`export { wrapPageElement } from './src/apollo/wrap-page-element';`

The above setup is the 'default' `gatsby-Apollo` setup, as far as I understand. 

Any tips would be helpful!

**Comment by edoardolunardi** [comment]
I would reopen this, since I have the same problem that leads to a content blink in production mode. 
Changing to `wrapPageElement` doesn't solve for me.

![flash](https://user-images.githubusercontent.com/34012860/90442885-a2ae1a00-e0db-11ea-844c-885714966c33.gif)

The weird thing is that if I inspect the page source, the `style` tags is correctly filled. I guess something is happening on client and the style tag gets empty.

<img width="788" alt="Screenshot 2020-08-17 at 22 44 59" src="https://user-images.githubusercontent.com/34012860/90442706-5bc02480-e0db-11ea-880a-b02c774cdbd3.png">

<img width="482" alt="Screenshot 2020-08-17 at 22 41 24" src="https://user-images.githubusercontent.com/34012860/90442445-f4a27000-e0da-11ea-8619-0e0d7cc00496.png">


In `gatsby-config.js`
```
    {
      resolve: `gatsby-plugin-styled-components`,
      options: {
        pure: true,
        displayName: process.env.NODE_ENV !== "production",
      },
    },
```

In`gatsby-browser.js`

```
import React from "react"
import GlobalStyles from "./src/styles/Global"
import Theme from "./src/components/theme"

export const wrapPageElement = ({ element }) => (
  <>
    <Theme>
      <GlobalStyles />
      {element}
    </Theme>
  </>
```

In `gatsby-ssr.js`
```
export { wrapPageElement } from "./gatsby-browser"
```

With

 `"babel-plugin-styled-components": "^1.11.1"`
`"gatsby-plugin-styled-components": "^3.3.10",`
`"styled-components": "^5.1.1",`


FYI `Theme` is just
```
import React from "react"
import { ThemeProvider } from "styled-components"

const theme = {
  something: "cool"
}

const Theme = ({ children }) => (
  <ThemeProvider theme={theme}>{children}</ThemeProvider>
)

export default Theme
```

**Comment by KishokanthJeganathan** [comment]
Im having this issue and I dont even use styled components. All I have is a global stled sheet that is being shared across the project by gatsby-browser.js. Has anyone had such an issue? :/

**Comment by johnchourajr** [comment]
I was having this issue and it was really bugging me. Weirdly, what I discovered is that I had two `gatsby-plugin-styled-components` entries in my `gatsby-config` file.

Before:
This was before I deployed that fix: https://602f5a74a59b8c00071245f4--johndesign.netlify.app/

After: 
This was after I made this commit ([see here](https://github.com/johnchourajr/john.design/commit/7a562807cf74f218b883f3c2cee55730f655886a)): https://602f5ad493dca3000856f93d--johndesign.netlify.app/

Really annoying. Hopefully this can be helpful for others.
