### ISSUE TITLE
navigation.js:173 Uncaught TypeError

### ISSUE THREAD

**Issue by t2ca** [gatsbyjs/gatsby#21139]
Updated my packages today and started getting this error when i click a link on my webpage.

```
navigation.js:173 Uncaught TypeError: Cannot read property 'getElementsByTagName' of null
    at navigation.js:173

```

```
  170 | if (document.title) {
  171 |   pageName = document.title
  172 | }
> 173 | const pageHeadings = document
  174 |   .getElementById(`gatsby-focus-wrapper`)
  175 |   .getElementsByTagName(`h1`)
  176 | if (pageHeadings && pageHeadings.length) {
```

**Comment by hatr1ck** [comment]
Same here

**Comment by heart-of-code** [comment]
Appears to have been introduced in this commit:
https://github.com/gatsbyjs/gatsby/commit/701222f76fbfe61bf4a519c5105baf91272cd221

**Comment by ehowey** [comment]
Just started hitting this too.

**Comment by marcysutton** [comment]
Same here, cc @madalynrose.

**Comment by Lc0rE** [comment]
I confirm to have hit this issue after upgrading to the latest `2.19.11` release.

**Comment by sidharthachatterjee** [comment]
Fix incoming

**Comment by ZeliosAriex** [comment]
Im having the same issue :(

**Comment by hupe1980** [comment]
Same here!

**Comment by mkidawa** [comment]
Experiencing same issue :<

**Comment by shameer-rahman** [comment]
Same here

**Comment by sidharthachatterjee** [comment]
Fixed and published in `gatsby@2.19.12`

Apologies for this.

**Comment by garrison0** [comment]
I seem to be getting this exact issue even after updating Gatsby to 2.19.12

**Comment by t2ca** [comment]
Try `rm -rf node_modules/`
make sure you have the latest version and install again

**Comment by garrison0** [comment]
checked for both reach/router and gatsby versions in the dependencies, then removed node_modules and re-installed

still getting the error

**Comment by john-tipper** [comment]
Same error for me, I have 2.19.12 and `@reach/router: 1.2.1`, blown away node_modules and everything else associated with my project and the error is still occurring.

**Comment by jodiedoubleday** [comment]
Yea same issue for me, interestingly my project works fine until I start using Gatsby Image, then the problem occurs on my homepage only `/pages/index`

**Comment by kushal9291** [comment]
Same issue. Was working fine until I start using MDXRenderer (gatsby-plugin-mdx)

**Comment by legarams** [comment]
Having the same issue

**Comment by chamod-gamage** [comment]
Having the same issue appear on a specific set of pages. Same code works fine on a Mac but not on my Windows machine. Tried different versions of Gatsby.

**Comment by RobertDanielsson** [comment]
Having the same issue,  "gatsby": "^2.19.19"

**Comment by grantmac** [comment]
Same issue "gatsby": "^2.19.12". Any work arounds as my Link is totally dead.

**Comment by LekoArts** [comment]
The original issue was solved and the reproduction steps mentioned here cannot reproduce it anymore. If you have further problems you can take a look at https://github.com/gatsbyjs/gatsby/issues/21263 so that we don’t have duplicate issues. Thanks!

**Comment by kimichen13** [comment]
> Having the same issue, "gatsby": "^2.19.19".
> 
> Edit: I fixed it. My components filename was "Search.js" and route was navigate("/search"). Renamed my file to search.js and it started working.

I rename the file in `page` from `Cart.js` to `cart.js`. It works. Thank you.

**Comment by EduGomes18** [comment]
I try all the steps above but i still getting this issue D:, rename files to lowercase, put all files in the src/pages root, using gatsby clean and also deleting node_modules and yarn.lock, i don`t know what more can i do to solve this, someone have a diferent way?

**Comment by Tony221268** [comment]
still 100% getting this error

**Comment by huynhpeter** [comment]
Just started running into this issue as well
