### ISSUE TITLE
Regression: `setNodeField` in plugin `index.js` file value is always `null`

### ISSUE THREAD

**Issue by crutchcorn** [gatsbyjs/gatsby#22287]
### Description

I'm trying to use `setNodeField` in a plugin of mine. However, instead of the value being set, there is simply `null` being set for the field's value. This code previously worked, but sometime recently on upgrading the `gatsby` versions, it does not work any longer, which is why I feel that this is a regression.

### Steps to reproduce

https://github.com/unicorn-utterances/unicorn-utterances/tree/integration

https://github.com/unicorn-utterances/unicorn-utterances/blob/integration/gatsby-config.js#L65

https://github.com/unicorn-utterances/unicorn-utterances/tree/integration/plugins/count-inline-code

https://github.com/unicorn-utterances/unicorn-utterances/blob/integration/plugins/count-inline-code/index.js

If you add `console.log(props)`, you should should see a value for `inlineCount`

https://github.com/unicorn-utterances/unicorn-utterances/blob/integration/src/templates/blog-post.tsx#L16

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

How to Make a Minimal Reproduction: https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/

### Expected result

What should happen?

The value set here:

https://github.com/unicorn-utterances/unicorn-utterances/blob/integration/plugins/count-inline-code/index.js#L21

Should be applied to the field value

### Actual result

The value is `null`, even though I can add a console.log to the plugin that shows the correct value

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

```
 System:
    OS: Windows 10 10.0.18363
    CPU: (12) x64 AMD Ryzen 5 1600 Six-Core Processor
  Binaries:
    Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.19.43 => 2.19.43
    gatsby-image: ^2.2.43 => 2.2.43
    gatsby-plugin-feed: ^2.3.28 => 2.3.28
    gatsby-plugin-google-analytics: ^2.1.37 => 2.1.37
    gatsby-plugin-lunr: ^1.5.2 => 1.5.2
    gatsby-plugin-manifest: ^2.2.47 => 2.2.47
    gatsby-plugin-offline: ^3.0.40 => 3.0.40
    gatsby-plugin-prefetch-google-fonts: ^1.4.3 => 1.4.3
    gatsby-plugin-react-helmet: ^3.1.23 => 3.1.23
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0
    gatsby-plugin-robots-txt: ^1.5.0 => 1.5.0
    gatsby-plugin-sass: ^2.1.30 => 2.1.30
    gatsby-plugin-sharp: ^2.4.12 => 2.4.12
    gatsby-plugin-sitemap: ^2.2.29 => 2.2.29
    gatsby-plugin-transition-link: ^1.18.0 => 1.18.0
    gatsby-plugin-typescript: ^2.2.3 => 2.2.3
    gatsby-remark-autolink-headers: ^2.1.25 => 2.1.25
    gatsby-remark-copy-linked-files: ^2.1.39 => 2.1.39
    gatsby-remark-external-links: 0.0.4 => 0.0.4
    gatsby-remark-images: ^3.1.49 => 3.1.49
    gatsby-remark-images-medium-zoom: ^1.4.0 => 1.4.0
    gatsby-remark-prismjs: ^3.3.35 => 3.3.35
    gatsby-remark-responsive-iframe: ^2.2.33 => 2.2.33
    gatsby-remark-video: ^1.2.5 => 1.2.5
    gatsby-source-filesystem: ^2.1.55 => 2.1.55
    gatsby-transformer-json: ^2.2.27 => 2.2.27
    gatsby-transformer-remark: ^2.6.58 => 2.6.58
    gatsby-transformer-sharp: ^2.3.18 => 2.3.18
```

**Comment by jlkiri** [comment]
If I add `inlineCount` manually to the query in the blog post, it is fetched properly. I personally have never seen using TS interface as GraphQL fragment so maybe that is the reason?

```
		markdownRemark(fields: { slug: { eq: $slug } }) {
			...PostInfo
			fields {
				inlineCount
			}
		}
```

**Comment by crutchcorn** [comment]
I apologize @jlkiri but I'm not sure I follow. As I understand the code, `PostInfo` **is** a GQL fragment here:

https://github.com/unicorn-utterances/unicorn-utterances/blob/integration/src/components/layout/layout.tsx#L113

My TS interface is just meant to enforce that GQL fragment (as I've yet to put in the time to figure out how to generate TS types from the fragments themselves)

**Comment by jlkiri** [comment]
@crutchcorn Ah, my bad. I didn't notice the fragment in `layout.tsx` and got confused.

**Comment by LekoArts** [comment]
> This code previously worked, but sometime recently on upgrading the gatsby versions, it does not work any longer, which is why I feel that this is a regression.

It would be important to know if this is actually true or some recent error in userland/your code. Can you pinpoint the version?

**Comment by crutchcorn** [comment]
Okay, I think I've pinpointed more specifically what's gone wrong. It doesn't seem that Gatsby version #s have got anything to do with it (apologies).

While this commit works:

https://github.com/unicorn-utterances/unicorn-utterances/pull/144/commits/c05a63ba2871f7ff1d57f9fb85eb4108278d9875

I had to upgrade dependencies at some point and when I did so, it gave me an error that I hadn't seen before:

```

 ERROR #85923  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "inlineCount" on type "MarkdownRemarkFields".

If you don't expect "inlineCount" to exist on the type "MarkdownRemarkFields" it is most likely a typo.
However, if you expect "inlineCount" to exist there are a couple of solutions to common problems:
```

So I figured I'd have to update the schema manually, so I did so:

https://github.com/unicorn-utterances/unicorn-utterances/pull/144/commits/8e02c69d3270ca8ffaf3e307c0574eb7f428a89a

It seems that THIS change (the `createSchemaCustomization` call) is what's returning `null` for the created fields. (on the commit I said was working, I just added this single file and sure enough `null` is yielded.

That said, I'm also confused now why the schema would need to be customized. Wouldn't this code:

https://github.com/unicorn-utterances/unicorn-utterances/blob/901ff83c5b5e20a46da4326028c7feb317a34932/plugins/count-inline-code/index.js

Run on every markdown file, therefore adding the type implicitly?

**Comment by jlkiri** [comment]
Apparently plugins for `gatsby-transformer-remark` are run within a call to `setFieldsOnGraphQLNodeType` API. What *should* happen when `createNodeField` is used within `setFieldsOnGraphQLNodeType`?

**Comment by crutchcorn** [comment]
I personally would love to see the `createNodeField` to work within a `remark` plugin. It seems to make logical sense and docs aren't clear enough to suggest otherwise. Alternatively, I think docs should be clearer about this (including a mention in the `createNodeField` docs)

**Comment by crutchcorn** [comment]
Furthermore, if I change the file to:

```javascript
const { GraphQLInt } = require("gatsby/graphql");
const flatFilter = require("unist-util-flat-filter");

const addInlineCount = ({ markdownAST }) => {
	const inlineCodeAST = flatFilter(
		markdownAST,
		node => node.type === "inlineCode"
	);
	let inlineWords = 0;
	if (inlineCodeAST && inlineCodeAST.children) {
		inlineWords = inlineCodeAST.children.reduce(
			(numberOfInline, inlineCodeNode) => {
				const { value } = inlineCodeNode;
				const words = value.split(/\b/g);
				return numberOfInline + words.length;
			},
			0
		);
	}

	return {
		inlineCount: {
			type: GraphQLInt,
			resolve: source => {
				return inlineWords;
			}
		}
	};
};

module.exports = addInlineCount;
```

I STILL get `null` as the value instead of what I might otherwise expect

**Comment by crutchcorn** [comment]
I'd love some guidance on how my code is _supposed_ to look in order to get the functionality I'm looking for. I've tried various methods to no avail and my progress on various tasks on my site is blocked as a result of my misunderstanding of the code mentioned.

**Comment by crutchcorn** [comment]
I finally see what you're saying @jlkiri regarding calling within a `setFieldsOnGraphQLNodeType.` I guess my question is: How are we supposed to be able to enable field creation from remarked plugins? I have two plugins that I'm hoping to add fields to, and I'd like to avoid recreating much of the AST functionality that remark is already doing for us.

Might we be able to change this:

https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-transformer-remark/src/extend-node-type.js#L173

To something of a reducer that we can then pass to the return value of `setFieldsOnGraphQLNodeType ` to at least provide some support that way? I'd be willing to make a PR to fix that if that's the method we want to move forward with

**Comment by crutchcorn** [comment]
Actually, confusingly, I think we have a mismatch in behavior from build and develop modes:

![image](https://user-images.githubusercontent.com/9100169/77489788-6d382580-6df6-11ea-9659-25145c0d0a13.png)

The above is from the built site that's fully deployed. The nodes have the respective field values from that method but not in develop mode.

**Comment by jlkiri** [comment]
@crutchcorn I confirmed that the behavior is different between build and develop.

**Comment by crutchcorn** [comment]
I found a new interesting thing here that I think is related:

If I take this branch and edit one of the markdown files after an `npm run develop` successfully loads, it will now `nullify` the fields I'm looking for:

https://github.com/unicorn-utterances/unicorn-utterances/tree/554ec01f3a42a882a05259a3e245bde82b602e7b

This is even despite not being `remarked` plugins anymore:

https://github.com/unicorn-utterances/unicorn-utterances/blob/554ec01f3a42a882a05259a3e245bde82b602e7b/plugins/remarked-autolink-headers-and-add-id/gatsby-node.js

**Comment by crutchcorn** [comment]
This issue is not stale. Are we able to remove the tag on it?

**Comment by hassankhan** [comment]
Just wanted to say I'm facing the same issue.

@crutchcorn Did you happen to find a workaround to this?

**Comment by graysonhicks** [comment]
Per [this comment](https://github.com/gatsbyjs/gatsby/issues/20684#issuecomment-586120263), this is resolved.  If anyone sees it again, feel free to open a new issue with a reproduction, thanks!

**Comment by crutchcorn** [comment]
@graysonhicks I could be wrong, but I am fairly certain those are two distinct issues 

One of them pertained to an old version while this one was created after on a new version.

AFAIK, this issue is still present

**Comment by LekoArts** [comment]
We'd need a reproduction of this on Gatsby 4

**Comment by LekoArts** [comment]
Hi!

I'm closing this as a stale issue as in the meantime Gatsby 4 and related packages were released. You can check our [Framework Version Support Page](https://www.gatsbyjs.com/docs/reference/release-notes/gatsby-version-support/) to see which versions currently receive active support.

Please try the mentioned issue on the latest version (using the `next` tag) and if you still see this problem, open a new bug report. It **must** include a [minimal reproduction](https://gatsby.dev/reproduction).

Thanks!
