### ISSUE TITLE
Hot reloading CSS broken when component lives in wrapPageElement

### ISSUE THREAD

**Issue by wesbos** [gatsbyjs/gatsby#23606]
## Description

I'm using Styled Components (and the gatsby plugin for it) but I can confirm this is an issue with CSS modules as well.

Hot reloading of CSS works great when you are editing a component on a page. 

However if you use the wrapPageElement or wrapRootElement API in `gatsby-browser.js` and have a styled component that lives in that layout, it's reloads the whole page - losing at state you might have. 

```js
export function wrapPageElement({ element, props }) {
  return <Layout {...props}>{element}</Layout>;
}
```

So for example, if I have a Layout component:

```js
export default function Layout({ children }) {
  return (
    <>
      <div>
          <Nav></Nav>
          {children}
      </div>
    </>
  );
}
```

And then either in Layout.js directry, or inside of another component - like Nav - I have my styled component:

```js
const NavStyles = styled.nav`
  background: green;
`;
```

Now if I change `green` to `blue`. The whole page reloads.

If I were to move that Nav component out of `Layout.js` and into a page like `pages/index.js`, it hot reloads fine without reloading the page.

### Environment

This happens in both Firefox and Chrome

  System:
    OS: macOS 10.15.2
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.9.0 - /usr/local/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.13.7 - /usr/local/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 81.0.4044.122
    Firefox: 59.0.1
    Safari: 13.0.4
  npmGlobalPackages:
    gatsby: 2.15.14

**Comment by wesbos** [comment]
Some more info:

I tried to just manually wrap every page in `<Layout>` and the issue persists.

I think this might not be related to wrapPageLayout, but nested components?

**Comment by pieh** [comment]
Are you sure about case of wrapping every page in `<Layout>` in this not working?

I can for sure reproduce this problem when using `wrapPageElement` (and `wrapRootElement`), but it worked fine when manually wrapping pages with layouts.

Just so there is no misunderstandings here - way I understand manually wrapping means to me something like we do in default starter - https://github.com/gatsbyjs/gatsby-starter-default/blob/95a4d12f3341460c638dde2fbf13c5f2c9b04cdc/src/pages/index.js#L9-L18 where each page uses `<Layout>` to wrap its content - is this what you tried or something else?

**Comment by pieh** [comment]
Can you also try running `GATSBY_HOT_LOADER=fast-refresh gatsby develop` and see how hot reloading works there? (that is available from `gatsby@2.19.39` onwards)

This will use `react-refresh` (over default `react-hot-loader`) and it seems like it handles it better (for `wrapPageElement` parts etc). It's still considered experimental ( https://www.npmjs.com/package/react-refresh ) and requires more recent version of `react` than what `gatsby@2` have as minimal so we can't really make that default yet, but we hope to switch to it in the future.

**Comment by chocobuckle** [comment]
@wesbos @pieh I was having the same problem and running ```GATSBY_HOT_LOADER=fast-refresh gatsby develop``` solved it, for me anyway. Would be nice to figure out what the cause of the original issue was though! ¯\_(ツ)_/¯

**Comment by wesbos** [comment]
Do you know if I can stick `GATSBY_HOT_LOADER=fast-refresh` in an .env file? I've tried `.env` and `.env.development`, but both are ignored. Not sure how well sticking it in package.json will work for windows users

**Comment by gaearon** [comment]
Is there a plan to switch to Fast Refresh by default? React Hot Loader is extremely fragile and I hope we can phase it out asap.

**Comment by pieh** [comment]
> Do you know if I can stick `GATSBY_HOT_LOADER=fast-refresh` in an .env file? I've tried `.env` and `.env.development`, but both are ignored. Not sure how well sticking it in package.json will work for windows users

Unfortunately this will likely not work right now. We are aware of this and do plan improvement and streamlining those for next major - https://github.com/gatsbyjs/gatsby/issues/21004 but those will need breaking changes so those are reserver for v3.

> Is there a plan to switch to Fast Refresh by default? React Hot Loader is extremely fragile and I hope we can phase it out asap.

Yes! We just can't do it in version 2 of Gatsby, because it still supports `react/react@dom@>=16.4.2` and while we where researching Fast Refresh we found in some of comments that it needs at least 16.10 (or so, I don't remember right now). This is planned for next major as well. I personally am also bit weary of disclaimer that currently there is in README for `react-refresh`:

```
This is an experimental package for hot reloading.

Its API is not as stable as that of React, React Native, or React DOM, and does not follow the common versioning scheme.

Use it at your own risk.
```

So we do hope that timing will align and `react-refresh` will be marked as stable before/during our v3 work.

**Comment by wesbos** [comment]
Shoot it seems like the new hot reloading works for CSS, but is broken for my react components. It gives me:

```js
Ignored an update to unaccepted module ./src/pages/index.js -> ./.cache/sync-requires.js -> ./.cache/app.js -> 0

[HMR] The following modules couldn't be hot updated: (Full reload needed)
This is usually because the modules which have changed (and their parents) do not know how to hot reload themselves. See https://webpack.js.org/concepts/hot-module-replacement/ for more details.

[HMR]  - ./src/pages/index.js 
```

And doesn't even refresh the page.

**Comment by gaearon** [comment]
What does your `./src/pages/index.js` look like?

**Comment by gaearon** [comment]
> I personally am also bit weary of disclaimer that currently there is in README for react-refresh

That's just a template we copy paste in all new packages. It's been used in React Native for almost a year now and is stable.

The part that needs work is *how* it's integrated. I'm assuming you are doing this via the current webpack plugin? That plugin needs more work to be good.

**Comment by wesbos** [comment]
@gaearon - looks like a restart solved it for now - will keep an eye on what causes if it if happens again

**Comment by chocobuckle** [comment]
@wesbos Are you using wrapPageElement or gatsby-plugin-layout? With wrapPageElement ```react-refresh/fash-refresh``` is working without problems for me, but I haven't tried it on a gatsby-plugin-layout project.

**Comment by wesbos** [comment]
I'm using wrapPageElement

**Comment by chocobuckle** [comment]
Ah, you sorted it out, good stuff. The ol' plug it-out-and-plug-it-back-in-again trick! :)

**Comment by gaearon** [comment]
You might want to track https://github.com/pmmmwh/react-refresh-webpack-plugin/issues/75. @timer has forked the plugin for Next, using a new webpack feature (which was also backported into 4.x) to improve the resilience. We need to get those changes merged back into the `react-refresh-webpack-plugin`. Then we want to upstream the plugin itself into React repo.

**Comment by blainekasten** [comment]
@gaearon I'm absolutely tracking all of this :) Here's our rough plan of action:

- take part in stabilizing the refresh plugin ecosystem and keep it incorporated with gatsby
- Gatsby V3 will raise the bar for minimum react version, which allows us to make fast-refresh the default dev experience
- continue to support hot-loader until preact is compatible with fast-refresh

Since fast-refresh should fix these rough edges for us, I don't think it's worth our effort fixing this in hot-loader as it will eventually be fully replaced.

**Comment by theKashey** [comment]
Oh. I am waiting for this for the half year.

**Comment by wesbos** [comment]
Still an issue, can be closed if Gatsby ships fast-refresh as default and this doesn't need fixing

**Comment by blainekasten** [comment]
Thanks @wesbos! It should be the default in v3
