### ISSUE TITLE
ERROR #85923 GRAPHQL: Type inference not working for gatsby >= 2.21.3

### ISSUE THREAD

**Issue by styxlab** [gatsbyjs/gatsby#23633]
## Description

After updating to gatsby version `>=2.21.3`, `gatsby develop` throws many errors of type `ERROR #85923 GRAPHQL`: There was an error in your GraphQL query during step "extract queries from components". Interestingly, `gatbsy build` works as expected.

### Steps to reproduce

```
$ git clone -b issue-gatsby-23633 https://github.com/styxlab/gatsby-starter-try-ghost.git
$ cd gatsby-starter-try-ghost
$ yarn
$ gatsby develop
```

Error log starting here:
```
success run queries - 0.717s - 28/28 39.08/s
warn Plugin `gatsby-transformer-rehype` tried to define the GraphQL type

 ERROR #85923  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "icon" on type "GhostSettings".

If you don't expect "icon" to exist on the type "GhostSettings" it is most likely a typo.
However, if you expect "icon" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development server
- The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have
- You want to optionally use your field "icon" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add a least one entry with that field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned "dummy content". Visit our docs to learn how you can define the schema for "GhostSettings":
https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions

File: node_modules/gatsby-theme-try-ghost/src/components/common/HeaderIndex.js:49:9
```

Note that `gatsby build` doesn't throw any errors and that the produced build is working as expected.

### Expected result

`gatsby develop` should be able to infer the types as it did before.

### Workaround

Ensure gatsby version `<=2.21.1`

### Related Issues

I thought that I'd be hit by issue #23472 but the fix should be already in the latest gastby build and the errors shown above still persist. Latest version that I tested was `2.21.6`.

New open Issue #23632 looks similar in its symptoms.

### Comparison between version `2.21.1` and `2.21.3`:

By looking through the changes between the working and not working version, my hunch is that [the changes in inference-metadata.js](https://diff.intrinsic.com/gatsby/2.21.1/2.21.3#file-dist__schema__infer__inference-metadata.js) are causing the issue.

### Environment
  System:
    OS: Linux 5.5 Fedora 30 (Workstation Edition) 30 (Workstation Edition)
    CPU: (8) x64 Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz
    Shell: 5.0.11 - /bin/bash
  Binaries:
    Node: 12.16.2 - /usr/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  Languages:
    Python: 2.7.17 - /usr/bin/python
  Browsers:
    Chrome: 81.0.4044.122
    Firefox: 75.0
  npmGlobalPackages:
    gatsby-cli: 2.11.14

**Comment by pieh** [comment]
Just one note - the branch pinned `gatsby` to `2.21.1` when I tried, so be sure to use `2.21.3` to reproduce

**Comment by vladar** [comment]
@styxlab This is not a bug in Gatsby but maybe a bug (which used to be a hack/workaround in the past?) in `gatsby-source-ghost`.

Sadly, they rely on internal Gatsby API and assume that GraphQL schema is static (and doesn't change after creation). But Gatsby recently introduced a schema rebuilding feature that updates your schema in `develop` on node changes (only on structural changes).

So the culprit is in those lines: https://github.com/TryGhost/gatsby-source-ghost/blob/master/gatsby-node.js#L128-L156

As you can see the "fake" nodes are being deleted on the internal `SET_SCHEMA` event. And those "fake" nodes essentially define the shape of your types (when there is no actual data).

Now Gatsby sees that some nodes were deleted and rebuilds the schema (at this moment those "fake" nodes do not exist anymore and there is no source for inference).

Recent changes in inference-metadata that you linked to simply revealed this problem.

I realize this was a quick workaround in `gatsby-source-ghost` to define the full schema for cases when there is no data available for inference. But we have [schema customization](https://www.gatsbyjs.org/docs/schema-customization/) now for this exact purpose.

So I suggest the following steps:

1. You should probably create an issue in `gatsby-source-ghost` repo about this with link to this comment and suggestion to start using [schema customization](https://www.gatsbyjs.org/docs/schema-customization/) instead of an old hack

2. In the meantime, we'll temporarily revert the recent change in Gatsby because it will probably affect others as well (as this pattern was likely used in several plugins)

**Comment by vladar** [comment]
Heh, I did a bit more digging and it's a bit more complicated. We actually introduced a bug in #23472 (which caused false positives for schema dirty checks).

But in a normal situation, it would simply cause one schema rebuilding in `develop` and wouldn't break. So my comment above about schema customization in `gatsby-source-ghost` still holds.

As for the bug in Gatsby - should be fixed in #23658

**Comment by styxlab** [comment]
@vladar Thanks a lot for digging into this. Does your latest finding mean that schema customization in `gatsby-source-ghost` is just a nice-to-have or will it break again once you re-introduce the (corrected) schema dirty check?

**Comment by vladar** [comment]
@styxlab This **may** still break in other edge cases if not fixed in `gatsby-source-ghost`.

**Comment by devzeaa96** [comment]
Hi! Any solution for this issue?. I use Gatsby CLI version: 3.1.0

**Comment by ntran-star** [comment]
I don't use `gatsby-source-ghost` but still encounter the same issue in `gatsby 3.13.1`. Any solution?

**Comment by patrykcode** [comment]
` ERROR #85923  GRAPHQL`
I had the same error, removing .cache helped

**Comment by Zara603** [comment]
I have this error :-(

**Comment by mailmonir** [comment]
ERROR #85923  GRAPHQL.VALIDATION

There was an error in your GraphQL query:

Cannot query field "mainPage" on type "WpPage".

If you don't expect "mainPage" to exist on the type "WpPage" it is most likely a typo. However, if you expect "mainPage" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node/gatsby-config, please try a restart of your development server.
- You want to optionally use your field "mainPage" and right now it is not used anywhere.

It is recommended to explicitly type your GraphQL schema if you want to use optional fields.

File: src\pages\index.js:30:7

See our docs page for more info on this error: https://gatsby.dev/creating-type-definitions

not finished  gatsby-source-wordpress  ingest WPGraphQL schema - 0.094s                                                                                                                                                                
not finished  gatsby-source-wordpress  diff schemas - 0.096s                                                                                                                                                                           
failed extract queries from components - 2.038s
