### ISSUE TITLE
bug(www): some plugin READMEs are not properly rendered

### ISSUE THREAD

**Issue by RohitChattopadhyay** [gatsbyjs/gatsby#24137]
## Description

Plugin description is not rendering the Readme file properly, instead only _README.md_ is visible.

### Steps to reproduce

Visit https://www.gatsbyjs.org/packages/gatsby-plugin-sass/

### Expected result
![image](https://user-images.githubusercontent.com/19877300/82118796-16682000-9797-11ea-964b-d4f37b58717e.png)

Readme `gatsby-plugin-sass` should be transformed the same way as for other plugins

### Actual result

What happened.
![image](https://user-images.githubusercontent.com/19877300/82118739-d7d26580-9796-11ea-9ca2-ffe7fcdf714b.png)

### Environment

Windows, checked in Chrome and Edge

**Comment by iamdarshshah** [comment]
**Similar Issues:** 
#16322
#13720
#11129

**Other Plugins with the same issue:**

- [ ] https://www.gatsbyjs.org/packages/gatsby-plugin-i18n/

- [ ] https://www.gatsbyjs.org/packages/gatsby-plugin-i18n-tags/

- [ ] https://www.gatsbyjs.org/packages/gatsby-plugin-i18n-readnext/

- [ ] https://www.gatsbyjs.org/packages/gatsby-plugin-sass-resources/?=gatsby-plugin-sass

- [ ] https://www.gatsbyjs.org/packages/bowlingx-gatsby-plugin-sass/?=gatsby-plugin-sass

- [ ] https://www.gatsbyjs.org/packages/gatsby-plugin-sass-resources/?=gatsby-plugin-sass

It seems that the issue still persists. @wardpeet can you check this? **(reference: #16322)**

**Comment by viveksharmaui** [comment]
Hi i wants to work on this issue.

**Comment by iamdarshshah** [comment]
@viveksharmaui sure go for it!!

**Comment by viveksharmaui** [comment]
Please assign me this issue so that i can start my work .

**Comment by iamdarshshah** [comment]
@viveksharmaui You can give it a try and request PR for this issue. The team will review your PR and will get back to you with the required changes if needed. Thanks

**Comment by viveksharmaui** [comment]
Sure! I will try

**Comment by viveksharmaui** [comment]
@iamdarshshah I'm struggling with setting up gatsby project can you help me? I want to run locally unable to regenerate this issue.

**Comment by RohitChattopadhyay** [comment]
> @iamdarshshah I'm struggling with setting up gatsby project can you help me? I want to run locally unable to regenerate this issue.

Please elaborate on the problem you are facing
https://github.com/gatsbyjs/gatsby/tree/master/www
This is the codebase of the concerned website

**Comment by viveksharmaui** [comment]
> > @iamdarshshah I'm struggling with setting up gatsby project can you help me? I want to run locally unable to regenerate this issue.
> 
> Please elaborate on the problem you are facing
> https://github.com/gatsbyjs/gatsby/tree/master/www
> This is the codebase of the concerned website

I have installed npm modules and run npm install but still facing error.

**Comment by RohitChattopadhyay** [comment]
> > > @iamdarshshah I'm struggling with setting up gatsby project can you help me? I want to run locally unable to regenerate this issue.
> > 
> > 
> > Please elaborate on the problem you are facing
> > https://github.com/gatsbyjs/gatsby/tree/master/www
> > This is the codebase of the concerned website
> 
> I have installed npm modules and run npm run dev but still facing error in development mode.

See if this helps https://www.gatsbyjs.org/contributing/website-contributions/

Adding screenshots/log of your error, will help a lot

**Comment by viveksharmaui** [comment]
> > > > @iamdarshshah I'm struggling with setting up gatsby project can you help me? I want to run locally unable to regenerate this issue.
> > > 
> > > 
> > > Please elaborate on the problem you are facing
> > > https://github.com/gatsbyjs/gatsby/tree/master/www
> > > This is the codebase of the concerned website
> > 
> > 
> > I have installed npm modules and run npm run dev but still facing error in development mode.
> 
> See if this helps https://www.gatsbyjs.org/contributing/website-contributions/
> 
> Adding screenshots/log of your error, will help a lot

![Screenshot from 2020-05-18 22-48-20](https://user-images.githubusercontent.com/28563357/82243864-bc638800-9959-11ea-8dd7-49f5b60a4cef.png)

**Comment by viveksharmaui** [comment]
I'm facing this issue on my system even tried to run `sudo apt install libvips-dev` on my linux mint.
I'm using node version `v12.16.1`

**Comment by viveksharmaui** [comment]
also tried to use node version `v10` according to this guide : https://www.gatsbyjs.org/docs/gatsby-on-linux/

but still facing same error.

**Comment by viveksharmaui** [comment]
Hi! I checked this issue and it is working fine in local I think it is production-related issue.

> **Similar Issues:**
> #16322
> #13720
> #11129
> 
> **Other Plugins with the same issue:**
> 
> * [ ]  https://www.gatsbyjs.org/packages/gatsby-plugin-i18n/
> * [ ]  https://www.gatsbyjs.org/packages/gatsby-plugin-i18n-tags/
> * [ ]  https://www.gatsbyjs.org/packages/gatsby-plugin-i18n-readnext/
> * [ ]  https://www.gatsbyjs.org/packages/gatsby-plugin-sass-resources/?=gatsby-plugin-sass
> * [ ]  https://www.gatsbyjs.org/packages/bowlingx-gatsby-plugin-sass/?=gatsby-plugin-sass
> * [ ]  https://www.gatsbyjs.org/packages/gatsby-plugin-sass-resources/?=gatsby-plugin-sass
> 
> It seems that the issue still persists. @wardpeet can you check this? **(reference: #16322)**

I tested this and it is occuring in 
1) gatsby-plugin-i18n
2) gatsby-plugin-i18n-tags
3) gatsby-plugin-i18n-readnext
4) gatsby-plugin-sass-resources
5) bowlingx-gatsby-plugin-sass
6) gatsby-plugin-sass-resources

this issue is not regenerated for gatsby-plugin-sass. It was rendered correctly on my system.

**Comment by ZachHoskins** [comment]
> **Similar Issues:**
> #16322
> #13720
> #11129
> 
> **Other Plugins with the same issue:**
> 
> * [ ]  https://www.gatsbyjs.org/packages/gatsby-plugin-i18n/
> * [ ]  https://www.gatsbyjs.org/packages/gatsby-plugin-i18n-tags/
> * [ ]  https://www.gatsbyjs.org/packages/gatsby-plugin-i18n-readnext/
> * [ ]  https://www.gatsbyjs.org/packages/gatsby-plugin-sass-resources/?=gatsby-plugin-sass
> * [ ]  https://www.gatsbyjs.org/packages/bowlingx-gatsby-plugin-sass/?=gatsby-plugin-sass
> * [ ]  https://www.gatsbyjs.org/packages/gatsby-plugin-sass-resources/?=gatsby-plugin-sass
> 
> It seems that the issue still persists. @wardpeet can you check this? **(reference: #16322)**

I am still having the same issue with all of these plugins as well as the following plugins:
 * [ ]  https://www.gatsbyjs.org/packages/gatsby-plugin-coffeescript/
 * [ ]  https://www.gatsbyjs.org/packages/gatsby-plugin-stylus/
 * [ ]  https://www.gatsbyjs.org/packages/gatsby-plugin-postcss/

I installed the Gatsby site locally on my machine, and I'm still getting the same issue locally.

![image](https://user-images.githubusercontent.com/50255197/85714513-1cafbd00-b6b0-11ea-8272-f799831fa289.png)

 @iamdarshshah, do you mind if I take a swing at this one to try to resolve this issue?

**Comment by iamdarshshah** [comment]
Sure @ZachHoskins Give it a try.

**Comment by ZachHoskins** [comment]
Now it looks like the issue is resolved. I looked through the PRs since I experienced the issue this morning, but I didn't find anything that specifically dealt with this issue. Here is a screenshot form the GraphQL query I ran this morning, and another that I ran just a few minutes ago after bringing my local repo up to date with the Gatsby one:

![image](https://user-images.githubusercontent.com/50255197/85816208-3f81b600-b730-11ea-97a8-c7178b94e310.png)

![image](https://user-images.githubusercontent.com/50255197/85816253-6344fc00-b730-11ea-8094-7e4f87365eed.png)

I think it's safe to say this issue is no longer an active issue. Perhaps a pull request that was approved today contained the fix for this issue in it.

**Comment by tesseralis** [comment]
I'm still seeing the invalid README pages on the described plugins so I don't think this issue is resolved just yet. @viveksharmaui are you still interested in helping with this issue?

**Comment by ZachHoskins** [comment]
I am also only seeing README.md on those pages now, but for some reason, it was displaying properly on the night of June 25. So I'm not quite sure why it went from not working to working and then back to not displaying properly again.

**Comment by marcysutton** [comment]
I'm still seeing this as well. It may help to look at the "Edit this page on GitHub" URLs, since they contain some clues. For example, the [i18n plugin page](https://www.gatsbyjs.org/packages/gatsby-plugin-i18n/) points to a search index: https://github.com/search?q=gatsby-plugin-i18n

**Comment by LekoArts** [comment]
As far as I remember those are issues with Algolia`s index and intermittent issues. Happy to read some more insights on that if you can find a culprit.

**Comment by NakaChans** [comment]
Sir Please assign me this issue so that i can start my work .

**Comment by LekoArts** [comment]
This should be solved with https://github.com/gatsbyjs/gatsby/pull/27040 once Aloglia updates its index.

**Comment by nbaosullivan** [comment]
Hey @LekoArts - #27040 was just specific to one package (gatsby-plugin-postcss) due to a redundant `readme` property in the `package.json` file

**Comment by LekoArts** [comment]
My colleague added a commit to your PR removing the same entry from the other packages mentioned here :)

**Comment by nbaosullivan** [comment]
Ah fantastic, thanks for letting me know 👍
