### ISSUE TITLE
[gatsby-remark-katex] allow usage of plugins

### ISSUE THREAD

**Issue by benabel** [gatsbyjs/gatsby#24763]
## Summary

I would like to use the `mhchem` package with gatsby-remark-katex

### Basic example

For this I would need to require the script after importing `katex` to modify katex behaviour like this:

```js
const katex = require('katex');
require('katex/dist/contrib/mhchem.js'); // modify katex module
```

As described here: https://github.com/KaTeX/KaTeX/pull/2178/files

### Motivation

Maybe it could be added with another key in the configuration objects something like:

```js
plugins: ['katex/dist/contrib/mhchem.js', ...]
```

**Comment by pieh** [comment]
Is there other way to "add" `mhchem` (and possibly other plugins / mods) than importing it after importing `katex` itself?

The problem with approach you proposed is that if we specify "require path" in `gatsby-config`, but actually require it in `gatsby-remark-katex` - we might hit module resolution problems:
If "plugin" is not in `katex` package itself but is from some other package we would try to import this other module in `gatsby-remark-katex`, but this one doesn't declare it as dependency - it's the site itself (or theme) that declares it. To illustrate:

We could potentially have `node_modules` structure like this:

```
- node_modules
  - gatsby-remark-katex
  - gatsby-theme-blah
    - node_modules
       - some-katex-plugin
```

And we add `some-katex-plugin` as `katex-plugin` - then we would "resolve" it in `gatsby-remark-katex` - but this one can't resolve `some-katex-plugin`.

**Comment by benabel** [comment]
In fact I did want to handle plugins like this:

```
{
            resolve: `gatsby-remark-katex`,
            options: { katexPlugins: ['katex/dist/contrib/mhchem.js'] },
          }
```

**Comment by pieh** [comment]
I might have been not entirely correct with my previous statement - there actually might be way to do it ... but it relies on using `plugins` (which is currently hardcoded special case plugin options in gatsby - https://github.com/gatsbyjs/gatsby/blob/100453cb8535cf6dd7e727ae67bf06330af1a23a/packages/gatsby/src/bootstrap/load-plugins/load.ts#L160-L168).

If you are interested in experimenting - in your site, navigate to `node_modules/gatsby-remark-katex` (or it might be somewhere else in `node_modules` depending how directory tree was resolved by package manager).

Inside it add `gatsby-node.js` file with following code:

```js
exports.onPreBootstrap = (_, pluginOptions) => {
  if (pluginOptions && pluginOptions.plugins && Array.isArray(pluginOptions.plugins)) {
    pluginOptions.plugins.forEach(plugin => {
      require(plugin.resolve)
    })
  }
}
```

Make sure that your `gatsby-config` is using `plugins` key for `gatsby-remark-katex` instance:

```js
{
  resolve: `gatsby-remark-katex`,
  options: { plugins: ['katex/dist/contrib/mhchem.js'] },
}
```

It might (or might not) "just work". If it doesn't - keeping the `gatsby-node` another thing is to try this:

```js
{
  resolve: `gatsby-remark-katex`,
  options: { plugins: [require.resolve('katex/dist/contrib/mhchem.js')] },
}
```

**Comment by benabel** [comment]
You're right this module is not resolved. None of these solutions works.

first solution:

    Error: Unable to find plugin "katex/dist/contrib/mhchem.js". Perhaps you need to install its package?

second solution:

     Error: Unable to find plugin "...node_modules/katex/dist/contrib/mhchem.js". Perhaps you need to install its package?

Even if this file exists.

**Comment by benabel** [comment]
The only solution I found was to require on the index.js file of the gatsby-remark-katex package:

```js
module.exports = ({ markdownAST }, pluginOptions = {}) => {
  if (
    pluginOptions &&
    pluginOptions.katexPlugins &&
    Array.isArray(pluginOptions.katexPlugins)
  ) {
    pluginOptions.katexPlugins.forEach((plugin) => {
      require(plugin)
    })
  }
  visit(markdownAST, `inlineMath`, (node) => {
    node.type = `html`
    node.value = katex.renderToString(node.value, {
      displayMode: false,
      ...pluginOptions,
    })
  })
  visit(markdownAST, `math`, (node) => {
    node.type = `html`
    node.value = katex.renderToString(node.value, {
      displayMode: true,
      ...pluginOptions,
    })
  })
}

```

With a plugin entry like this:

```js
{
            resolve: `gatsby-remark-katex-mhchem`,
            options: {
              katexPlugins: ['katex/dist/contrib/mhchem.js'],
            },
          },

```

**Comment by pieh** [comment]
> You're right this module is not resolved. None of these solutions works.

Here's the code that throws "Unable to find plugin" - https://github.com/gatsbyjs/gatsby/blob/de1db4b4658f6a1a09a6c3df374e5c9d48fed0c3/packages/gatsby/src/bootstrap/load-plugins/load.ts#L87-L124

After checking this - we expect that "plugin` is it's own package - which means that we expect there is `package.json` file there :/ It makes sense for gatsby plugins, but not necesairly for non-gatsby plugins...

There is a way to make it work still bit it's getting convoluted - wrapper package could be created (let's call it `gatsby-remark-katex-mhchem`) that would have `peerDependency` on `katex` (same as `gatsby-remark-katex`) and just 2 files - `package.json` and `index.js` and inside `index.js` we could just import 'katex/dist/contrib/mhchem.js' - then gatsby would be happy about plugin structure and because we could use `plugins` we would be shielded from potential problems with module resolutions

> The only solution I found was to require on the index.js file of the gatsby-remark-katex package

Hmm yea, but this solution will not work every time - as soon as `node_modules` will be constructed by package manager (`npm`, `yarn`, `pnpm`, etc) differently it will start breaking.

**Comment by benabel** [comment]
It seems quite complicated to handle this change for every katex plugin and every package manager so I go for a local plugin that I've called `gatsby-remark-katex-mhchem` with the `require` added in the index.js.

```js
'use strict'

const visit = require(`unist-util-visit`)

const katex = require(`katex`)

const remarkMath = require(`remark-math`)

require('katex/dist/contrib/mhchem.js') // modify katex module

module.exports = ({ markdownAST }, pluginOptions = {}) => {
  visit(markdownAST, `inlineMath`, (node) => {
    node.type = `html`
    node.value = katex.renderToString(node.value, {
      displayMode: false,
      ...pluginOptions,
    })
  })
  visit(markdownAST, `math`, (node) => {
    node.type = `html`
    node.value = katex.renderToString(node.value, {
      displayMode: true,
      ...pluginOptions,
    })
  })
}

module.exports.setParserPlugins = () => [remarkMath]
```

Thanks for your support. As usual the gatsby team is really incredible.

I close the issue and paste my code if some tries to use this plugin.
