### ISSUE TITLE
`gatsby develop` errors out when port 8000 is in use

### ISSUE THREAD

**Issue by laurieontech** [gatsbyjs/gatsby#25621]
Previously, if 8000 was in use the CLI would ask whether I wanted to run on another port.

It appears this behavior is broken as I see this instead.

<img width="975" alt="Screen Shot 2020-07-08 at 3 24 26 PM" src="https://user-images.githubusercontent.com/15000607/86961811-db97be00-c12f-11ea-8dc7-16bf98571cb7.png">

To Reproduce:
- Run a gatsby project using `gatsby develop`
- Attempt to run `gatsby develop` for another project while the first is still running

**Comment by josephmarkus** [comment]
Got exactly the same issue. Can no longer run two different Gatsby instances

```
➜  [...] git:(master) yarn start
yarn run v1.22.4
$ cross-env NODE_ENV=development gatsby develop
[...]/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: listen EADDRINUSE: address already in use 127.0.0.1:8000
    at Server.setupListenHandle [as _listen2] (net.js:1313:16)
    at listenInCluster (net.js:1361:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1498:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:68:8)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1340:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '127.0.0.1',
  port: 8000
}
error Command failed with exit code 7.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
➜  [...] git:(master)
```

**Comment by johno** [comment]
I've confirmed this is now fixed in `gatsby@2.24.9` thanks to @mxstbr so going to go ahead and close this.

**Comment by chrispytoes** [comment]
I am attempting to update an older site from `gatsby@2.32.12` to `gatsby@3.4.0`, and I am running into this error now. I am not trying to run it on a different port, and I am not running a second instance of Gatsby anywhere.


```
E:\projects\gatsby\gatsby-site-will-county-fair\node_modules\yoga-layout-prebuilt\yoga-layout\build\Release\nbind.js:53
        throw ex;
        ^

Error: listen EADDRINUSE: address already in use 127.0.0.1:58167
    at Server.setupListenHandle [as _listen2] (net.js:1318:16)
    at listenInCluster (net.js:1366:12)
    at GetAddrInfoReqWrap.doListen (net.js:1503:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:8)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1345:8)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '127.0.0.1',
  port: 58167
}
error while proxying request: read ECONNRESET
error Command failed with exit code 7.
```

I deleted my `node_modules` and `package-lock.json`, and started from scratch with my dependencies, carefully upgrading each one to the requirements for `gatsby@3.4.0`. All the dependencies are resolved now, and I get this error at the end of running `gatsby develop` now.

If it means anything, I remember getting this error a few times a while back when I started this project but I don't remember how I fixed it at the time.

**Comment by josephmarkus** [comment]
@chrispytoes is it possible that you have another project running on that port? I sometimes have a few terminal windows open and forget that one port is already taken up by another project.

There a few ways to have a look at what is on a particular port. Try looking up "mac check what's running on port" or similar, based on the platform that you're using 👍

**Comment by chrispytoes** [comment]
@josephmarkus Ah, well that looks like what the problem was. After a restart, it's working now.

However, I definitely didn't have any other projects open, and I checked Task Manager and closed all node.js processes and the issue was still occurring. Only restarting fixed it. Not sure if that was Gatsby or something else on my PC, but I wasn't running any other servers that I knew of at the time.

**Comment by josephmarkus** [comment]
@chrispytoes glad it worked. Sometimes you might have some hanging process somewhere taking up space.
