### ISSUE TITLE
gatsby-source-filesystem ->Error: EPERM: operation not permitted, open

### ISSUE THREAD

**Issue by AleC77** [gatsbyjs/gatsby#30113]
## Description

run -> gatsby build
gatsby-source-filesystem looks don't work in OS: Windows 10 10.0.19041. 
It works in ubuntu. 

FYI: it works with gatsby develop

### Steps to reproduce

Done building

### Expected result

Done building

### Actual result

failed to process file.pdf
Error: EPERM: operation not permitted, open
'.cache\caches\gatsby-source-filesystem\tmp-7b17c8c1e6d1803fc8fa2cac31a6d818.pdf'

not finished source and transform nodes - 362.452s
failed Remote file download - 239.020s

### Environment

  System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
  Binaries:
    Node: 12.14.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.423.0), Chromium (89.0.774.48)
  npmPackages:
    gatsby: ^3.0.4 => 3.0.4 
    gatsby-image: ^3.0.0 => 3.0.0 
    gatsby-plugin-gdpr-cookies: ^1.0.14 => 1.0.14 
    gatsby-plugin-google-tagmanager: ^3.0.0 => 3.0.0 
    gatsby-plugin-iltorb: ^1.0.0 => 1.0.0 
    gatsby-plugin-image: ^1.0.0 => 1.0.0 
    gatsby-plugin-manifest: ^3.0.0 => 3.0.0 
    gatsby-plugin-offline: ^4.0.0 => 4.0.0 
    gatsby-plugin-react-helmet: ^4.0.0 => 4.0.0 
    gatsby-plugin-sass: ^4.0.2 => 4.0.2 
    gatsby-plugin-sharp: ^3.0.0 => 3.0.0 
    gatsby-plugin-sitemap: ^3.0.0 => 3.0.0 
    gatsby-plugin-styled-components: ^4.0.0 => 4.0.0 
    gatsby-plugin-svgr: ^3.0.0-beta.0 => 3.0.0-beta.0 
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4 
    gatsby-plugin-zopfli: ^2.0.0 => 2.0.0 
    gatsby-remark-embed-video: ^3.1.0 => 3.1.0 
    gatsby-remark-images: ^4.0.0 => 4.0.0 
    gatsby-remark-responsive-iframe: ^3.0.0 => 3.0.0 
    gatsby-source-drupal: ^4.0.0 => 4.0.0 
    gatsby-source-filesystem: ^3.0.0 => 3.0.0 
    gatsby-transformer-json: ^3.0.0 => 3.0.0 
    gatsby-transformer-remark: ^3.0.0 => 3.0.0 
    gatsby-transformer-sharp: ^3.0.0 => 3.0.0 
  npmGlobalPackages:
    gatsby-cli: 3.0.0

**Comment by thandaanda** [comment]
We are also facing the same issue. Error occurs in Windows 10/WSL 1, works on Ubuntu.

NPM Packages: 
"@mdx-js/mdx": "^1.6.18",
"@mdx-js/react": "^1.6.18",
"@tailwindcss/typography": "^0.2.0",
"autoprefixer": "^9.7.4",
"babel-preset-gatsby": "^1.0.0",
"build-url": "^6.0.1",
"classnames": "^2.2.6",
"cssnano": "^4.1.10",
"disqus-react": "^1.0.8",
"gatsby": "^3.0.2",
"gatsby-awesome-pagination": "^0.3.5",
"gatsby-image": "^3.0.0",
"gatsby-plugin-catch-links": "^3.0.0",
"gatsby-plugin-feed": "^3.0.0",
"gatsby-plugin-force-trailing-slashes": "^1.0.4",
"gatsby-plugin-image": "^1.0.0",
"gatsby-plugin-manifest": "^3.0.0",
"gatsby-plugin-mdx": "^2.0.0",
"gatsby-plugin-mdx-embed": "^0.0.19",
"gatsby-plugin-netlify": "^3.0.0",
"gatsby-plugin-nprogress": "^3.0.0",
"gatsby-plugin-page-creator": "^3.0.0",
"gatsby-plugin-postcss": "^4.0.0",
"gatsby-plugin-purgecss": "^5.0.0",
"gatsby-plugin-react-helmet": "^4.0.0",
"gatsby-plugin-remove-generator": "^1.0.5",
"gatsby-plugin-sharp": "^3.0.0",
"gatsby-plugin-sitemap": "^3.0.0",
"gatsby-plugin-typescript": "^3.0.0",
"gatsby-source-filesystem": "^3.0.0",
"gatsby-transformer-sharp": "^3.0.0",
"html-react-parser": "^1.2.3",
"lodash": "^4.17.19",
"mdx-embed": "^0.0.19",
"node-sass": "^5.0.0",
"prism-react-renderer": "^1.1.1",
"prismjs": "^1.19.0",
"react-gist": "^1.2.2",
"react-helmet": "^6.1.0",
"react-medium-image-zoom": "^4.3.1",
"react-photo-gallery": "^8.0.0",
"reading-time": "^1.2.0",
"tailwindcss": "^1.6.0"

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

To make the process of resolving problems quicker for both sides we need you to fill out the issue template and give us a minimal reproduction:

```md
<!--
  Please fill out each section below, otherwise, your issue will be closed. This info allows Gatsby maintainers to diagnose (and fix!) your issue as quickly as possible.

  Useful Links:
  - Documentation: https://www.gatsbyjs.com/docs/
  - How to File an Issue: https://www.gatsbyjs.com/contributing/how-to-file-an-issue/

  Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
-->

## Description

Describe the issue that you're seeing.

### Steps to reproduce

Clear steps describing how to reproduce the issue. **Please** link to a reproduction, this makes your issue _much_ easier to diagnose (seriously).

How to Make a Minimal Reproduction: https://www.gatsbyjs.com/contributing/how-to-make-a-reproducible-test-case/

### Expected result

What should happen?

### Actual result

What happened.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.
```

**Comment by AleC77** [comment]
> Hi, thanks for the issue!
> 
> To make the process of resolving problems quicker for both sides we need you to fill out the issue template and give us a minimal reproduction:
 

I thought I did it. I repeat here below.

==========================

## Description

run -> gatsby build
gatsby-source-filesystem looks don't work in OS: Windows 10 10.0.19041. 
It works in ubuntu. 

FYI: 
- it works with gatsby develop
- I use Visual Studio

### Steps to reproduce

Done building

### Expected result

Done building

### Actual result

failed to process file.pdf
Error: EPERM: operation not permitted, open
'.cache\caches\gatsby-source-filesystem\tmp-7b17c8c1e6d1803fc8fa2cac31a6d818.pdf'

not finished source and transform nodes - 362.452s
failed Remote file download - 239.020s

### Environment

  System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
  Binaries:
    Node: 12.14.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.423.0), Chromium (89.0.774.48)
  npmPackages:
    gatsby: ^3.0.4 => 3.0.4 
    gatsby-image: ^3.0.0 => 3.0.0 
    gatsby-plugin-gdpr-cookies: ^1.0.14 => 1.0.14 
    gatsby-plugin-google-tagmanager: ^3.0.0 => 3.0.0 
    gatsby-plugin-iltorb: ^1.0.0 => 1.0.0 
    gatsby-plugin-image: ^1.0.0 => 1.0.0 
    gatsby-plugin-manifest: ^3.0.0 => 3.0.0 
    gatsby-plugin-offline: ^4.0.0 => 4.0.0 
    gatsby-plugin-react-helmet: ^4.0.0 => 4.0.0 
    gatsby-plugin-sass: ^4.0.2 => 4.0.2 
    gatsby-plugin-sharp: ^3.0.0 => 3.0.0 
    gatsby-plugin-sitemap: ^3.0.0 => 3.0.0 
    gatsby-plugin-styled-components: ^4.0.0 => 4.0.0 
    gatsby-plugin-svgr: ^3.0.0-beta.0 => 3.0.0-beta.0 
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4 
    gatsby-plugin-zopfli: ^2.0.0 => 2.0.0 
    gatsby-remark-embed-video: ^3.1.0 => 3.1.0 
    gatsby-remark-images: ^4.0.0 => 4.0.0 
    gatsby-remark-responsive-iframe: ^3.0.0 => 3.0.0 
    gatsby-source-drupal: ^4.0.0 => 4.0.0 
    gatsby-source-filesystem: ^3.0.0 => 3.0.0 
    gatsby-transformer-json: ^3.0.0 => 3.0.0 
    gatsby-transformer-remark: ^3.0.0 => 3.0.0 
    gatsby-transformer-sharp: ^3.0.0 => 3.0.0 
  npmGlobalPackages:
    gatsby-cli: 3.0.0

**Comment by LekoArts** [comment]
I'm afraid I still can't reproduce this on my Mac or Windows 10 with WSL. As the error suggests and you can see in other issues this seems to be caused by missing permissions of your current user:

- https://github.com/gatsbyjs/gatsby/issues/30179
- https://github.com/gatsbyjs/gatsby/issues/25658
- https://github.com/gatsbyjs/gatsby/issues/16353

So make sure that your Windows user has enough permissions for your current directory. Especially, "write" permissions as the plugin tries to write a file to your hard drive.

**Comment by vladadaba** [comment]
I was getting this same error during both `yarn build` and `yarn develop`. Figured it was due to timeout during `source and transform nodes` phase (default timeout is 30 seconds). Adding these env vars increased the timeout and let me build/start the app:

```
CONNECTION_TIMEOUT=600000
STALL_RETRY_LIMIT=10
STALL_TIMEOUT=60000
GATSBY_CONCURRENT_DOWNLOAD=1
```

**Comment by qubis741** [comment]
@vladadaba mister, you are genius and lifesaver! your solution is perfect

**Comment by uno-b** [comment]
I'm having the same issue. Adding the said env variables didn't fix the problem, unfortunately.

**Comment by Chinomso1995** [comment]
@vladadaba, perfect solution.
