### ISSUE TITLE
[gatsby-plugin-image]: loading=eager causes blurred image in production mode, sharpens after page interaction

### ISSUE THREAD

**Issue by ehowey** [gatsbyjs/gatsby#31031]
## Description

The logo image on my website is remaining blurred in production after page load and sharpens after page interaction. This does not occur for any other images that I can see, however I have reproduced it on one other site I manage as well.

- Does not occur in Safari/FF
- Does occur in Chrome/Edge (Chromium)
- Does not occur with a cold cache, e.g. incognito mode

The website is using a number of interloocking themes and the logo is contained is nested in a Layout component so it is rendered on each page. The query for the logo itself is happening in the "core" theme in the `useSiteMetadata` hook.  The query is a bit atypical as it looks for a unique name "catalyst-site-logo" which was a decision I made long ago and a piece of technical debt. Here is what that query looks like:

```
logo: file(name: { eq: "catalyst-site-logo" }) {
          childImageSharp {
            gatsbyImageData(
              height: 300
              layout: CONSTRAINED
              placeholder: BLURRED
            )
          }
        }
```

Relevant file: https://github.com/ehowey/gatsby-theme-catalyst/blob/main/themes/gatsby-theme-catalyst-core/src/utils/use-site-metadata.js

The logo is then displayed in the branding component which is actually contained in the site which consumes the theme, in this case my own site. Here is what that looks like:

```jsx
<Link
        to="/"
        onClick={() => setIsNavOpen(false)}
        sx={{ textDecoration: "none" }}
      >
        <GatsbyImage
          image={logo}
          sx={{
            height: ["40px", "50px", null, "60px", null],
            width: ["61px", "76px", null, "96px", null],
            filter: isNavOpen ? "invert(1)" : "none",
            variant: "variants.siteLogo",
          }}
          alt={title}
          objectFit="contain"
          loading="eager"
          imgStyle={{ objectFit: "contain" }}
        />
      </Link>
```

Relevant file: https://github.com/ehowey/erichoweydev/blob/master/src/components/header/branding.js

You can view a live example of this at: https://www.erichowey.dev/

###Video

https://user-images.githubusercontent.com/204841/115956370-83149000-a4b9-11eb-99bd-d0a3212a012b.mp4

### Steps to reproduce

You can fork and deploy my site if you want a live example to play with, but note this _will not_ be present in local development. 

https://github.com/ehowey/erichoweydev

Goto : https://www.erichowey.dev/

1. Load site in Chrome/Edge (should load and look fine)
2. Close browser window.
3. Reload site again (logo should be blurry)
4. Interact with page, click some links etc (logo should sharpen)

### Expected result

Logo should sharpen like all other images.

### Actual result

Logo remains blurred until page interaction in Chromium browsers.

### Environment

Not relevant, as this is a production bug. Site is hosted with Netlify if that matters.

### My guess

I think this is a caching issue. Something to do with how Chromium is handling and detecting that image, either due to it being in a Layout component (which is present on each page), maybe due to the query being "by name" and not by "relative path" is causing a hashing issue? 

### Other notes

Possibly related to:  https://github.com/gatsbyjs/gatsby/issues/30671

I also checked on Twitter - and others see a blurry logo as well. So it is not specific to my computer/system.

**Comment by t2ca** [comment]
I also see a blurry logo after a reload in chrome.  However when i open dev tools and click reload, i don't see this issue.

Have you tried StaticImage instead of GatsbyImage?

**Comment by ehowey** [comment]
Yea I had thought of doing that but was...lazy...I just tried tonight and am now doing it like this:

```
<Link
        to="/"
        onClick={() => setIsNavOpen(false)}
        sx={{ textDecoration: "none" }}
      >
        <StaticImage
          src="./eh-logo.png"
          placeholder="blurred"
          sx={{
            height: ["40px", "50px", null, "60px", null],
            width: ["61px", "76px", null, "96px", null],
            filter: isNavOpen ? "invert(1)" : "none",
            variant: "variants.siteLogo",
          }}
          alt={title}
          objectFit="contain"
          loading="eager"
          imgStyle={{ objectFit: "contain" }}
        />
      </Link>
```

I am now thinking this maybe has to do with my conditional filtering.   Basically I am using isNavOpen as a flag to flip the colors of the image when the mobile menu is open.  I am going to remove that and see if it fixes itself.

**Comment by ehowey** [comment]
Okay I tracked this down by trial and error. Note my site will no longer show a blurred logo.

The culprit was `loading="eager"`. Somehow that was causing the problems. When I remove that prop it works fine.  Note I also removed the `objectFit="contain"` just because I didn't need the polyfill, but I tested a few different variations and it was just the loading=eager that made the difference.

Here is the working code:

```
<StaticImage
          src="./eh-logo.png"
          placeholder="blurred"
          sx={{
            height: ["40px", "50px", null, "60px", null],
            width: ["61px", "76px", null, "96px", null],
            filter: isNavOpen ? "invert(1)" : "none",
            variant: "variants.siteLogo",
          }}
          alt={title}
          // loading="eager"
          imgStyle={{ objectFit: "contain" }}
        />
```

**Comment by byronlanehill** [comment]
Has there been any update on this? I have a site which has four small images above the fold and they are appearing blurry in production when loading="eager", but I'd like to load the images as soon as possible.

**Comment by zremboldt** [comment]
Our team is experiencing this issue as well. We're turning off loading='eager' until the bug is resolved.

**Comment by jaredhill4** [comment]
I'm experiencing a similar issue.

I'm trying to use the same logo image from my CMS in multiple places: once in the header (navbar) and once in the footer (both persist across all views).

Depending on the scroll position, only one of the logos will load, while the other will remain blurred until a page interaction.

For example, if I reload the page while the scroll position is at the top of the page, the logo in the header will load, but when I scroll down to the footer, I see that it remains blurry. But if I reload the page while scrolled down to the footer, the footer logo will load, while the header logo remains blurry.

The link to test is: https://capitolcityatx.org/

This is occurring in:
- Chrome for iOS
- Safari for iOS

**Comment by ehowey** [comment]
Yeah so the repro above is obviously not minimal, and I fixed it for myself by removing the `loading=eager` - but my recollection is that yes this was only an issue in production.

**Comment by ehowey** [comment]
I just tested this again another time and I can still replicate it on my site if I add l`loading=eager` to the logo file.

You can see the file here: https://github.com/ehowey/erichoweydev/blob/master/src/components/layout/header/branding.js

**Comment by halidovz** [comment]
Also had the same issue. Ended up setting the placeholder's opacity to 0 in the `onLoad` callback of `GatsbyImage`. 

something like

```tsx
<GatsbyImage
  ...props
  onLoad={() => {
    // querying placeholder DOM element here and setting its opacity to 0
  }}
/>
```

**Comment by lambdadev007** [comment]
I am having the same issue too and @halidovz's solution is also not working. I think onLoad event is not fired at all when the issue is occurred.

**Comment by SimonScholz** [comment]
This also still happens on my site in chrome. And it looks even worse than just blurred:

![image](https://user-images.githubusercontent.com/7559962/212846255-a7479cb0-9c81-4fcf-8ff7-79ed1083702a.png)

And this is how it should look like (after refreshing the page two times):

![image](https://user-images.githubusercontent.com/7559962/212846411-95c7c3b5-3364-437e-9141-e5f4eac24afb.png)

**Comment by EdwardGoomba** [comment]
Im not even seeing the optional prop for `loading` on `GatsbyImage`.
Using version `3.13.1` - passing in `loading='eager'` continues to result in the image rendering as lazy loading.

`Screenshot of img element after padding in eager to loading prop`
<img width="599" alt="Screenshot 2024-05-15 at 8 19 48 PM" src="https://github.com/gatsbyjs/gatsby/assets/12971857/fb8fdfcb-f5ac-4245-ae0c-8991126a72f1">
