### ISSUE TITLE
Gatsby Build Fail: Invariant Violation with GraphQL Type

### ISSUE THREAD

**Issue by mpaarating** [gatsbyjs/gatsby#3212]
## Description

Gatsby build suddenly fails (seemed to begin failing over night on webhook deployments).

### Environment

Gatsby version: 1.9.134
Node.js version: 6.9.4
Operating System: OSX 10.12.6

### File contents (if changed):

`gatsby-config.js`: 
``` javascript
module.exports = {
  plugins: [
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-source-contentful`,
      options: {
        spaceId: `redacted`,
        accessToken: `redacted`
      }
    },
    `gatsby-transformer-remark`,
    `gatsby-plugin-glamor`,
    {
      resolve: `gatsby-plugin-typography`,
      options: {
        pathToConfigModule: `src/utils/typography`
      }
    }
  ]
};
```
`package.json`: 
``` json
{
  "name": "personal-blog",
  "description": "Alex M Lewis Blog",
  "version": "1.0.0",
  "author": "Alex Lewis <alexmichael.lewis@gmail.com>",
  "dependencies": {
    "gatsby": "^1.9.127",
    "gatsby-link": "^1.6.30",
    "gatsby-plugin-glamor": "^1.6.10",
    "gatsby-plugin-react-helmet": "^1.0.8",
    "gatsby-plugin-typography": "^1.7.10",
    "gatsby-source-contentful": "^1.3.29",
    "gatsby-transformer-remark": "^1.7.24",
    "glamorous": "^4.11.0",
    "lodash": "^4.17.4",
    "typography-theme-irving": "^0.15.10"
  },
  "license": "MIT",
  "main": "index.js",
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "format": "prettier --trailing-comma es5 --no-semi --single-quote --write \"src/**/*.js\""
  },
  "devDependencies": {
    "prettier": "^1.9.0"
  }
}
```
`gatsby-node.js`: 
``` javascript
const Promise = require(`bluebird`);
const path = require(`path`);
const slash = require(`slash`);

exports.createPages = ({ graphql, boundActionCreators }) => {
  const { createPage } = boundActionCreators;
  return new Promise((resolve, reject) => {
    graphql(`
      {
        allContentfulPost {
          edges {
            node {
              slug
            }
          }
        }
      }
    `).then(result => {
      if (result.errors) {
        reject(result.errors);
      }

      // Create Product pages
      const productTemplate = path.resolve(`./src/templates/post-page.js`);
      // We want to create a detailed page for each
      // product node. We'll just use the Contentful id for the slug.
      result.data.allContentfulPost.edges.map(({ edge }) => {
        createPage({
          // Each page is required to have a `path` as well
          // as a template component. The `context` is
          // optional but is often necessary so the template
          // can query data specific to each page.
          path: `/${edge.node.slug}/`,
          component: slash(productTemplate),
          context: {
            slug: edge.node.slug
          }
        });
      });
    });
    resolve();
  });
};
```
`gatsby-browser.js`: No change
`gatsby-ssr.js`: No change

### Actual result

```
10:20:37 AM: Fetch Contentful data: 216.303ms
10:20:37 AM: success source and transform nodes — 0.372 s
10:20:37 AM: error Encountered an error trying to infer a GraphQL type for: "createdEntries___NODE". There is no corresponding node with the id field matching: "null"
10:20:37 AM: 

  Error: Invariant Violation: Encountered an error trying to infer a GraphQL typ  e for: "createdEntries___NODE". There is no corresponding node with the id fie  ld matching: "null"
  
  - invariant.js:42 invariant
    [repo]/[invariant]/invariant.js:42:15
  
  - infer-graphql-type.js:265 validateLinkedNode
    [repo]/[gatsby]/dist/schema/infer-graphql-type.js:265:5
  
  - infer-graphql-type.js:340 inferFromFieldName
    [repo]/[gatsby]/dist/schema/infer-graphql-type.js:340:3
  
  - infer-graphql-type.js:580 
    [repo]/[gatsby]/dist/schema/infer-graphql-type.js:580:23
  
  - lodash.js:4944 
    [repo]/[lodash]/lodash.js:4944:15
  
  - lodash.js:3001 baseForOwn
    [repo]/[lodash]/lodash.js:3001:24
  
  - lodash.js:4913 
    [repo]/[lodash]/lodash.js:4913:18
  
  - lodash.js:9359 Function.forEach
    [repo]/[lodash]/lodash.js:9359:14
  
  - infer-graphql-type.js:554 inferObjectStructureFromNodes
    [repo]/[gatsby]/dist/schema/infer-graphql-type.js:554:5
  
  - build-node-types.js:239 createNodeFields
    [repo]/[gatsby]/dist/schema/build-node-types.js:239:34
  
  - build-node-types.js:79 fields
    [repo]/[gatsby]/dist/schema/build-node-types.js:79:26
  
```

### Expected behavior

It should be building.

### Steps to reproduce

1\. Create a new gatsby project with `gatsby new project-folder`

2\. Replace the above files with their respective contents

3\. `gatsby develop`

I have tried removing all GraphQL related queries and am still running into the the issue. Any help/ideas is greatly appreciated!
...

**Comment by KyleAMathews** [comment]
My guess is this PR that I merged/released last night is affecting you https://github.com/gatsbyjs/gatsby/pull/3158

Could you try pinning gatsby-source-contentful to the release previous to yesterday's release?

Any help debugging this would be appreciated!

/cc @sarahatwork

**Comment by mpaarating** [comment]
@KyleAMathews It definitely seems to be an issue with gatsby-source-contentful. Once I remove it (and the associated graphql/config code), the site builds. I rolled back to 1.3.29 and 1.3.30, but it still fails with both of those. I'm still playing with it to see what version it _does_ build with.

**Comment by sarahatwork** [comment]
@mpaarating Can you roll back the version to 1.3.28? That was the previous version before yesterday's update to 1.3.29

**Comment by mpaarating** [comment]
@sarahatwork  :/ Still failing with the same issue. I wonder if Contentful changed something in their api that is causing an unexpected type coming back. I'm shooting in the dark though as I'm pretty new to both gatsby and Contentful.

**Comment by sarahatwork** [comment]
@mpaarating I think I've seen an error like that before from having corrupt data on Contentful, like if you have an association that's been deleted. Might this be the cause?

<img width="840" alt="screenshot 2017-12-15 15 04 41" src="https://user-images.githubusercontent.com/11855531/34058512-4bd0f54c-e1a9-11e7-9d85-79950ff95c0e.png">

**Comment by mpaarating** [comment]
@sarahatwork You were totally correct. Somehow an association with one of the start posts got deleted. Thank you so much for your time in helping to debug this!

**Comment by sarahatwork** [comment]
@mpaarating Good to hear!

Hopefully this problem will be fixed in a more permanent solution when we figure out a better way to make GraphQL schemas than relying on Contentful data (a good write-up of the issue is here: https://github.com/gatsbyjs/gatsby/issues/2392#issuecomment-340810897).

**Comment by jordan314** [comment]
FWIW, we started getting this error when we had an asset with the same ID as an entry ID.
