### ISSUE TITLE
Catch and handle "The result of this StaticQuery could not be fetched"

### ISSUE THREAD

**Issue by aaronadamsCA** [gatsbyjs/gatsby#33956]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

When an outdated component attempts to fetch stale static query data from the server, the entire site crashes.

While this issue involves the same error message as #26563, I don't understand what @wardpeet and @sidharthachatterjee have been tasked with solving in that issue. I am reporting a specific reproducible crash.

Gatsby should be able to tolerate a component fetching a static query data JSON file that no longer exists on the server.

### Reproduction Link

N/A. This is very hard to reproduce minimally.

### Steps to Reproduce

This set of steps will dependably crash any site in Chrome or Edge:

1. Implement a component that implements `useStaticQuery`.
1. Deploy to Gatsby Cloud.
1. Open the site in a browser, wait for it to finish loading, then close the tab.
1. Make a small edit to the static query, like switching the order of two fields.
1. Deploy to Gatsby Cloud.
1. Reopen the tab.

### Expected Result

The page opens, possibly after a refresh.

### Actual Result

The site crashes:

1. The old chunk is reloaded from the disk cache (due to `cache-control: public, max-age=31536000, immutable`).
1. The old chunk tries to reload its static query data JSON file from the server (due to `cache-control: public, max-age=0, must-revalidate`).
1. The server responds with a 404.
1. The component throws `Uncaught Error: The result of this StaticQuery could not be fetched.`
1. The site crashes.

One possible solution would be similar to #33844, and would probably involve refreshing the page. An ideal version of this solution would protect against a refresh loop, too.

### Environment

Gatsby Cloud. This doesn't reproduce using gtsb.io or `gatsby serve`, since these don't use Gatsby's recommended caching headers. This issue only occurs when caching chunks.

**Comment by aaronadamsCA** [comment]
So far this is very difficult to reproduce **minimally** due to Gatsby's Webpack configuration. It tends to aggressively merge chunks in a small site.

Is there a way to ask Gatsby to give a specific component its own chunk?

**Comment by graysonhicks** [comment]
@aaronadamsCA You can use gatsby-plugin-loadable-components-ssr to chunk at the component level.

**Comment by aaronadamsCA** [comment]
@graysonhicks Great idea, unfortunately it looks like loadable components work very differently from "organic" chunks and don't trigger this issue.

I'll keep working on reproducing in an isolated environment.

**Comment by graysonhicks** [comment]
@aaronadamsCA Ah yes, that's true.

**Comment by aaronadamsCA** [comment]
Until I can reproduce separately, I'll at least provide some solid evidence of it reproducing in my production environment.

I pushed a commit with a very short diff:

![image](https://user-images.githubusercontent.com/1505561/142069935-d6fd9845-5698-41a4-a987-35255d747781.png)

After it deployed I refreshed; no crash. So I reverted and started thinking of other ideas.

Then, suddenly, a crash when I reopened a tab:

![image](https://user-images.githubusercontent.com/1505561/142069536-00c5f7aa-ced5-4142-a0bc-68f7ed2e1dd7.png)

Unfortunately the dev tools were closed during that page load, so I don't have the network log. The stack trace, however, points directly to the change I made in `location-select-dialog.tsx`. The dev tools show the unreverted code, however by then the revert had deployed; so I'm quite sure the cached component tried downloading the asset that no longer existed, triggering the crash.

**Comment by aaronadamsCA** [comment]
Interestingly, reopening a closed Edge/Chrome tab seems to be the easiest way to reproduce this. It appears to reliably push the browser cache into an unexpected state.

**I want to stress that reopening an Edge/Chrome tab is not the only way to trigger this bug.** It's arrived in our logs from iOS Safari, and I've also experienced it when waking a sleeping tab on Android. But it's definitely making reproduction easier.

I managed to get a partial DevTools capture of a crash; unfortunately even with `--auto-open-devtools-for-tabs`, Edge doesn't capture the very beginning, but I think I've got a good picture.

**The most interesting detail (assuming DevTools isn't lying!) is that the trigger appears to be a mismatch between the `webpack-runtime-[hash].js` Gatsby asks for vs. the one it actually gets.**

You can see the mismatch here:

![image](https://user-images.githubusercontent.com/1505561/142077176-9703cf16-d1d0-4e85-8d5a-be25db1f5ee7.png)

The browser downloads a page that asks for new code, but then for whatever reason it executes old code anyway.

Even if this is a browser bug - even if every StaticQuery bug ever captured turns out to be caused by various browser bugs - I still think Gatsby needs an error boundary in core that will catch this error and refresh the page. I'm going to try building an error boundary like that tomorrow, to at least try to make our own sites immune to this issue.

I'll continue to share my findings.

**Comment by aubertinp** [comment]
Hello, we experience the same issue with our website. 
Each time, we push in production, we need to clear the cache for each user. It's a major issue because it's a public website and we do not have any solution to force them to clear their cache.

**Comment by aaronadamsCA** [comment]
I've had success catching and handling this error, as well as #33844, by writing a plugin that implements an error boundary.

<details><summary><code>core-error-boundary.tsx</code></summary>

```tsx
import type { ReactNode } from "react";
import { Component } from "react";

interface Props {
  children: ReactNode;
}

interface State {
  error: Error | null;
}

export class CoreErrorBoundary extends Component<Props, State> {
  public state: State = {
    error: null,
  };

  public componentDidCatch(error: Error): void {
    this.setState({ error });

    if (
      // https://github.com/gatsbyjs/gatsby/issues/33844
      error.name === "ChunkLoadError" ||
      // https://github.com/gatsbyjs/gatsby/issues/33956
      error.message.startsWith(
        "The result of this StaticQuery could not be fetched"
      )
    ) {
      // TODO: Somehow limit to a single refresh to prevent a refresh loop?
      window.location.reload();
    } else {
      throw error;
    }
  }

  public render(): ReactNode {
    return this.state.error ? null : this.props.children;
  }
}
```

</details>

<details><summary><code>gatsby-browser.js</code></summary>

```js
import { CoreErrorBoundary } from "./src/core-error-boundary";

export const wrapPageElement = ({ element }) => (
  <CoreErrorBoundary>{element}</CoreErrorBoundary>
);
```

</details>

<details><summary><code>gatsby-ssr.js</code></summary>

```js
export { wrapPageElement } from "./gatsby-browser";
```

</details>

I don't have prior experience writing error boundaries, so I have no idea if what I've done here is okay; but it seems to work fine. It handles the errors it's meant to handle, and leaves the rest of them to Sentry.

The biggest remaining gap is that it doesn't resolve the infinite reload loop problem that currently exists if an asset really is missing on the server.

We can try this in production to see if it works. If so, rather than releasing this as an optional plugin, maybe this could make for a good built-in plugin?

**Comment by graysonhicks** [comment]
Thanks @aaronadamsCA!  That looks right for a React error boundary in general.  I'm not sure where this would live in core.  I know there is an error boundary when in dev mode, but I don't think there is one in prod currently.  Only other question is, would someone ever want these errors to surface to Sentry?  What is the UX when this boundary is in place?

**Comment by aaronadamsCA** [comment]
We're well into opinion territory now, of course, but:

- If you `catch` a normal error in core, including an error thrown by a core dependency, I don't expect to know about it, receive it, or be able to handle it.
- I see this as the same thing; if the only way to "catch" a particular error in core is with an error boundary, then I think core should ship that error boundary, and I don't expect to know it's there.
- Put another way, somewhere in your internal docs I think there should be a description of each alternate path sequence when each type of critical asset (chunk, page data, or static query data) is unavailable. 99.9% of the time this condition is transient, and a reload will either resolve it, or push a user to the browser's "you are offline" page. Both are strongly preferable to the current situation.

I'm an intermediate React dev and in over my head with these errors, so take the above with a huge grain of salt, naturally. I'm just desperate to get these app crashes fixed ASAP, because users _really_ don't expect web apps to crash.

**Comment by graysonhicks** [comment]
@KyleAMathews Would love to get your take on this pattern for addressing these two common errors (StaticQuery result and  ChunkLoadError).

**Comment by aaronadamsCA** [comment]
Not sure what the difference is today, but with this deployed, the boundary definitely isn't catching any Webpack loader errors, they're still surfacing as uncaught.

Since "The result of this StaticQuery could not be fetched" is thrown from the actual `useStaticQuery` hook, I'm pretty sure the error boundary is still going to work for that. I'm testing now in production to confirm.

Maybe this issue would be limited to solving this error, possibly with an error boundary; and then the other ChunkLoadError issue could be about making the existing solution for Webpack errors more robust and improving the coverage.

**Comment by aaronadamsCA** [comment]
Confirmed, the error boundary successfully catches this error in production.

Screenshot showing that I was able to reproduce a StaticQuery error, but the page loaded anyway, due to the automatic reload:

![image](https://user-images.githubusercontent.com/1505561/143454614-2be08567-fa94-421f-8c62-0f4da153e274.png)

This error wasn't delivered to Sentry either, since this new inner error boundary caught it first.

So, this is a good general pattern I think Gatsby could adopt to handle alt-path rendering errors.

I'd maybe suggest adopting a common error class for these kinds of fatal, probably-transient rendering errors, too, so that the boundary could catch by name instead of by parsing the message.

**Comment by graysonhicks** [comment]
What happens to the component(s) that were relying on that StaticQuery?

**Comment by aaronadamsCA** [comment]
Since the error triggers a window reload, the component has a second chance to fetch its data; and since the initial fetch failure is transient, it works the second time.

(Note how the console shows the error, then a "navigated to" message; that's because I've enabled "preserve log" in my console to observe behaviour across multiple pageloads. So when you `console.error()` followed by `window.location.reload()`, this is what you see.)

It's literally the exact same solution as @KyleAMathews's ChunkLoadError workaround - when in doubt, reload the page - which also assumes errors are transient.

Both solutions fall down when there's an actual Webpack error; they induce a refresh loop, as opposed to a simple broken page. But given that's an extreme edge case, I'm thinking that could be solved further down the road. This solves the actual "Gatsby is crashy after deploys" issue that drives so many bug reports (which, in fairness, is exactly what the error message suggests should be done).

**Comment by pieh** [comment]
@aaronadamsCA We merged https://github.com/gatsbyjs/gatsby/pull/34225 (for now available with `gatsby@next`, but will be included in next `@latest`).

The way I could reproduce this problem somewhat reliably always revolved around using cached HTML from previous build (which would use previous js bundles), that would fetch new "data files" (from newer builds) and if queries would be edited between those builds it would cause error like this.

The problems I could see was not that network requests for static queries failed/404ed. It was that wrong static queries were fetched (not the ones that loaded (old) js bundle expected). We added a integrity check so runtime can know if loaded html+js is matching data files and if not - force single reload (note about refresh loop is completely valid, so we do setup flag with session storage to prevent refresh loop).

**Comment by aaronadamsCA** [comment]
That's very cool, love the improvement @pieh and thank you for the explanation! Once this releases I'll try removing our custom error boundary to confirm it's no longer required.

**Comment by aaronadamsCA** [comment]
Our traffic is very low right now due to post-holiday lull, but I merged #34225 a few days back and I haven't seen a single error with this message since. I'm gonna call this resolved, and I'll reopen if needed.

Thank you!

**Comment by andrasnagydev** [comment]
Hi,

some of our users are running into an error on our live site deployed with Gatsby Cloud.

We have `"gatsby": "^4.13.1"` in our package.json, and we are running Node version v16.13.2.

As a result, these users can only see a blank page, without any content.

The console errors in Chrome:

`
framework-944355198c46eb754888.js:2 Error: The result of this StaticQuery could not be fetched.

This is likely a bug in Gatsby and if refreshing the page does not fix it, please open an issue in https://github.com/gatsbyjs/gatsby/issues
    at f (app-b4b209617a37ca23459f.js:1:50289)
    at Z (component---src-pages-index-jsx-4eaf94c710501125512b.js:1:18320)
    at oo (framework-944355198c46eb754888.js:2:59965)
    at Ku (framework-944355198c46eb754888.js:2:112046)
    at Li (framework-944355198c46eb754888.js:2:99319)
    at Ni (framework-944355198c46eb754888.js:2:99247)
    at Pi (framework-944355198c46eb754888.js:2:99110)
    at bi (framework-944355198c46eb754888.js:2:96097)
    at hi (framework-944355198c46eb754888.js:2:93453)
    at es (framework-944355198c46eb754888.js:2:109538)
cu @ framework-944355198c46eb754888.js:2
framework-944355198c46eb754888.js:2 Uncaught Error: The result of this StaticQuery could not be fetched.

This is likely a bug in Gatsby and if refreshing the page does not fix it, please open an issue in https://github.com/gatsbyjs/gatsby/issues
    at f (app-b4b209617a37ca23459f.js:1:50289)
    at Z (component---src-pages-index-jsx-4eaf94c710501125512b.js:1:18320)
    at oo (framework-944355198c46eb754888.js:2:59965)
    at Ku (framework-944355198c46eb754888.js:2:112046)
    at Li (framework-944355198c46eb754888.js:2:99319)
    at Ni (framework-944355198c46eb754888.js:2:99247)
    at Pi (framework-944355198c46eb754888.js:2:99110)
    at bi (framework-944355198c46eb754888.js:2:96097)
    at hi (framework-944355198c46eb754888.js:2:93453)
    at es (framework-944355198c46eb754888.js:2:109538)
E0FA82093C08E271.png:1          Failed to load resource: the server responded with a status of 404 ()
`

We have not experienced this problem in other browsers.

“Clear cache and build” on Gatsbly Cloud did not change the result.

I have found:

https://www.gatsbyjs.com/docs/reference/release-notes/v4.5/#gracefully-handling-browser-cache-issues

So I wanted to let you know we are still (likely) facing this issue, and because we are looking for a workaround.

---

The problem in more detail (which may be unnecessary, but just in case it helps):

The error only affects pages users have already visited before a certain date - i.e. subpages users never visited run correctly even if other pages fail, or, if a user has never visited the site before that date, there are no problems on any of the pages.

If we run a hard refresh on the blank page, the page opens correctly, however if we right after that run a normal refresh, the site is blank again and so on.

**Comment by aaronadamsCA** [comment]
@andrasnagydev You may wish to file a separate issue; but in my limited experience with the (broken) offline plugin, if you don't immediately replace it with the plugin that removes its service worker, then an error is expected.

**Comment by HarleySalas** [comment]
2023 and still having this issue. In v5 now and I have never had the offline plugin; Is there anything in particular that I'm supposed to do? Pretty surprising with a very small e-commerce site, without very much plugin bloat, or weird configurations, that users in a production site just get a bit fat white screen until they hard refresh the page.

**Comment by wesleylhandy** [comment]
I'm also in v5 of a production site for a major client. We are struggling to reproduce, but we have gotten users sending us screenshots with the `The result of this StaticQuery could not be fetched`. We deploy to Netlify. Of course locally, and even on my devices in production I cannot reproduce it. But some users are having this problem

```sh
System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 18.17.1 - /tmp/yarn--1697077226976-0.8279363511358151/node
    Yarn: 1.22.19 - /tmp/yarn--1697077226976-0.8279363511358151/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
  Browsers:
    Chrome: 118.0.5993.70
  npmPackages:
    gatsby: ~5.11.0 => 5.11.0
    gatsby-background-image: ~1.6.0 => 1.6.0
    gatsby-plugin-anchor-links: ~1.2.1 => 1.2.1
    gatsby-plugin-gdpr-cookies: ~2.0.9 => 2.0.9
    gatsby-plugin-image: ~3.11.0 => 3.11.0
    gatsby-plugin-layout: ~4.11.0 => 4.11.0
    gatsby-plugin-manifest: ~5.11.0 => 5.11.0
    gatsby-plugin-netlify: ~5.1.1 => 5.1.1
    gatsby-plugin-react-helmet: ~6.11.0 => 6.11.0
    gatsby-plugin-remove-serviceworker: ~1.0.0 => 1.0.0
    gatsby-plugin-robots-txt: ~1.8.0 => 1.8.0
    gatsby-plugin-sass: ~6.11.0 => 6.11.0
    gatsby-plugin-sharp: ~5.11.0 => 5.11.0
    gatsby-plugin-sitemap: ~6.11.0 => 6.11.0
    gatsby-plugin-styled-components: ~6.11.0 => 6.11.0
    gatsby-plugin-typescript: ~5.11.0 => 5.11.0
    gatsby-source-contentful: ~8.11.0 => 8.11.0
    gatsby-source-filesystem: ~5.11.0 => 5.11.0
    gatsby-transformer-remark: ~6.11.0 => 6.11.0
    gatsby-transformer-sharp: ~5.11.0 => 5.11.0
```
