### ISSUE TITLE
Examples using-drupal errors

### ISSUE THREAD

**Issue by paulrobertpine** [gatsbyjs/gatsby#4397]
When I try running **gatsby develop** in the using-drupal example I get the following errors at the terminal:

`
error Plugin gatsby-source-drupal returned an error

  Error: Request failed with status code 404
  
  - createError.js:16 createError
    [using-drupal]/[axios]/lib/core/createError.js:16:15
  
  - settle.js:18 settle
    [using-drupal]/[axios]/lib/core/settle.js:18:12
  
  - http.js:191 IncomingMessage.handleStreamEnd
    [using-drupal]/[axios]/lib/adapters/http.js:191:11
  
  - next_tick.js:74 _combinedTickCallback
    internal/process/next_tick.js:74:11
  
  - next_tick.js:98 process._tickCallback
    internal/process/next_tick.js:98:9

error gatsby-node.js returned an error

GraphQL Error There was an error while compiling your site's GraphQL queries.
  Invariant Violation: GraphQLParser: Unknown field `allRecipes` on type `RootQueryType`. Source: document `IndexPageQuery` file: `GraphQL request`.
`
and the following errors in the browser:

`
TypeError: Cannot read property 'topRecipe' of undefined
IndexPage.render
src/pages/index.js:13
  10 | class IndexPage extends React.Component {
  11 |   render() {
  12 |     const data = this.props.data
> 13 |     const topRecipe = data.topRecipe.edges[0].node
  14 |     const nextTwoPromotedRecipes = data.nextTwoPromotedRecipes.edges.map(
  15 |       edge => edge.node
  16 |     )
`

**Comment by pieh** [comment]
Hey, I just fixed this with https://github.com/gatsbyjs/gatsby/pull/4391 - so update Your repository and update Your packages and You should be good to go.

**Comment by paulrobertpine** [comment]
​Thanks​, but now I get:

error UNHANDLED REJECTION



  RangeError: Maximum call stack size exceeded



  - RegExp.[Symbol.replace]



  - RegExp.[Symbol.replace]



  - String.replace



  - lodash.js:14174 deburr

    [using-drupal]/[lodash]/lodash.js:14174:31



  - lodash.js:4982 Function.camelCase

    [using-drupal]/[lodash]/lodash.js:4982:34



  - create-type-name.js:8 createTypeName

    [using-drupal]/[gatsby]/dist/schema/create-type-name.js:8:23



  - infer-graphql-input-fields.js:142 inferGraphQLInputFields

    [using-drupal]/[gatsby]/dist/schema/infer-graphql-input-fields.js:142:19



  - infer-graphql-input-fields.js:245

    [using-drupal]/[gatsby]/dist/schema/infer-graphql-input-fields.js:245:17



  - lodash.js:4917

    [using-drupal]/[lodash]/lodash.js:4917:15



  - lodash.js:3002 baseForOwn

    [using-drupal]/[lodash]/lodash.js:3002:24



  - lodash.js:4886

    [using-drupal]/[lodash]/lodash.js:4886:18



  - lodash.js:9334 Function.forEach

    [using-drupal]/[lodash]/lodash.js:9334:14



  - infer-graphql-input-fields.js:209 inferInputObjectStructureFromNodes

    [using-drupal]/[gatsby]/dist/schema/infer-graphql-input-fields.js:209:5



  - infer-graphql-input-fields.js:149 inferGraphQLInputFields

    [using-drupal]/[gatsby]/dist/schema/infer-graphql-input-fields.js:149:22



  - infer-graphql-input-fields.js:245

    [using-drupal]/[gatsby]/dist/schema/infer-graphql-input-fields.js:245:17



  - lodash.js:4917

    [using-drupal]/[lodash]/lodash.js:4917:15



  - lodash.js:3002 baseForOwn

    [using-drupal]/[lodash]/lodash.js:3002:24



  - lodash.js:4886

    [using-drupal]/[lodash]/lodash.js:4886:18



  - lodash.js:9334 Function.forEach

    [using-drupal]/[lodash]/lodash.js:9334:14



  - infer-graphql-input-fields.js:209 inferInputObjectStructureFromNodes

    [using-drupal]/[gatsby]/dist/schema/infer-graphql-input-fields.js:209:5



  - infer-graphql-input-fields.js:149 inferGraphQLInputFields

    [using-drupal]/[gatsby]/dist/schema/infer-graphql-input-fields.js:149:22



  - infer-graphql-input-fields.js:245

    [using-drupal]/[gatsby]/dist/schema/infer-graphql-input-fields.js:245:17

**Comment by pieh** [comment]
update `gatsby` package to latest and this will be fixed:
`npm --save install gatsby@latest`

**Comment by paulrobertpine** [comment]
Thank you but still not working. Now I get:

GraphQL Error There was an error while compiling your site's GraphQL
queries.

  Invariant Violation: GraphQLParser: Unknown field `localFile` on type
`files`. Source: document `IndexPageQuery` file: `GraphQL request`.

and in the browser I get:

TypeError: Cannot read property 'topRecipe' of undefined
IndexPage.render
src/pages/index.js:13
10 | class IndexPage extends React.Component {
11 | render() {
12 | const data = this.props.data
> 13 | const topRecipe = data.topRecipe.edges[0].node
14 | const nextTwoPromotedRecipes = data.nextTwoPromotedRecipes.edges.map(
15 | edge => edge.node
16 | )

**Comment by pieh** [comment]
Did you do any changes to example site? As a last resort - try stopping gatsby develop, deleting `.cache` directory and running gatsby develop again.

**Comment by KyleAMathews** [comment]
Also make sure you run `git pull` to get the latest version of using-drupal
