### ISSUE TITLE
Tutorial part six sort not working

### ISSUE THREAD

**Issue by hazelnusse** [gatsbyjs/gatsby#4585]
I'm probably doing something wrong but I don't know JS/React/Gatsby to know what I'm missing. In GraphiQL, I have:
```
{
  allMarkdownRemark(
    sort: { fields: [frontmatter___date], order: ASC}
  ) {
    edges {
      node {
        frontmatter {
          title
          date(formatString: "DD MMMM, YYYY")
        }
        excerpt
        timeToRead
        html
      }
    }
  }
}
```

and changing the `ASC` to `DESC` changes the order of the returned result as one would expect. However, when I place this query in `src/pages/index.js`, the order on the index page is always the same, regardless of whether I choose `ASC` or `DESC`. Restarting the development server made no difference. Adding new blog entries works, but something about the sorting is not working.

**Comment by hazelnusse** [comment]
Changing the date in the mardown file changes the order in the generated page, indicating that the entries are being sorted. However, changing the Graphql query above doesn't change the order as expected.

**Comment by vprasanth** [comment]
I tried to record the steps in commits as I went through the tutorial, maybe it can help. So far I can't see any issues with your query.. 

Here is my changeset for that part of the tutorial https://github.com/vprasanth/gatsby-practice-graphql/commit/d767e3f3bb58dd3d1d3dd5e3364505cf54532ce1

**Comment by hazelnusse** [comment]
I'm trying to root cause this and am noticing if I complete the steps incrementally as they are described in tutorial part 4, I get errors such as `TypeError: children is not a function` on `index.js`, but if don't run the `gatsby develop` step until I've made all the edits to get the various .js files in their final state, the page is built and works fine.
Does tutorial 4 work for you if you complete the steps verbatim as they are on the website?

**Comment by twhiteaker** [comment]
Maybe a separate issue, but sort doesn't work for me because there is no date on the frontmatter object. I'm using:
-- gatsby@1.9.247
gatsby cli 1.1.50
node v8.10.0
Windows 10 64-bit

![frontmatter](https://user-images.githubusercontent.com/699496/38585306-00dd8438-3cdf-11e8-856a-88be521d93c0.PNG)

**Comment by shannonbux** [comment]
Hi Tim!

Just to double check; did you include dates in your .md files?

Like this:

--- title: "Sweet Pandas Eating Sweets" date: "2017-08-10" ---

If so, did you restart the dev server after installing the
gatsby-transformer-remark plugin? That is necessary in order for GraphiQL
to reflect all the information in the markdown files.

One other thing that could have happened is that parts 4 and 5 might
include some instructions that are necessary to complete before part 6.

If you have carefully followed all instructions from part 4 through part 6
and are still running into this error, let me know and I'm curious to know
more. We could screen share so I can possibly see what's going wrong!

Shannon

**Comment by twhiteaker** [comment]
I did include dates in my md files, I restarted the dev server after installing the plug-in, and I started with part four from scratch in a fresh directory just to be sure, to the same effect.  I also noticed that while my frontmatter has a title attribute, its value is empty.

I am using the Node.js command prompt on Windows 10 64-bit as administrator (regular node is blocked).  I'm using Node.js 8.10.0 (x64).

Screen sharing sounds great!  April 12 is pretty open for me.

**Comment by shannonbux** [comment]
Hi Tim!

I was in workshops for a couple days. Will you put a time on my calendar
and we'll screenshare? calendly.com/shannon-soper

:) I'm very curious to see what is happening!

**Comment by twhiteaker** [comment]
My issue is different from the OP.  I created a new one at #5024.

**Comment by 7h3kk1d** [comment]
I'm having the same issue. It's in someway related to caching. If I blow away the .cache directory and rerun `gatsby develop` the change applies. It also happens for any change to the sorting/filtering logic. If I change the sort to a `limit: 1` no effect till I blow away .cache and restart. 

npm 6.1.0
node v10.1.0
gatsby 1.9.250
arch linux

**Comment by 7h3kk1d** [comment]
Also of note that the results from the iGraphQL interface seem to be correct when pasting the query from the code. So I'm not sure why those aren't being cached.

**Comment by FlashBlaze** [comment]
> 
> 
> Also of note that the results from the iGraphQL interface seem to be correct when pasting the query from the code. So I'm not sure why those aren't being cached.

Were you able to figure out the solution?
As you said, it works on iGraphQl but not on the actual posts page. And it works temporarily after clearing the cache. This also does not work on [Vercel](https://vercel.com) formerly Zeit where I have deployed my site.
Thanks

**Comment by BenoKop** [comment]
Hello i'm new to gatsby and i'm getting this error by doing the tutorial today...
Any tricks ?

Thanks.

**Comment by SleepWalker** [comment]
The bug is still there. The issue appeared after upgrading to gatsby@4.
